/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/instances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List server instances with pools and executors. */
    get: operations["listInstances"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign in with email and password. Sets the sluice_session cookie. */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign out and delete the current session. */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return the current user. */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the own profile. */
    patch: operations["updateMe"];
    trace?: never;
  };
  "/api/v1/auth/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change the own password. Other sessions are signed out. */
    post: operations["changePassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/sessions/revoke-others": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign out all other sessions of the current user. */
    post: operations["revokeOtherSessions"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users. */
    get: operations["listUsers"];
    put?: never;
    /** Create a user with a temporary password. */
    post: operations["createUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: components["parameters"]["UserId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change the name or role of a user, or disable or enable the user. */
    patch: operations["updateUser"];
    trace?: never;
  };
  "/api/v1/users/{userId}/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: components["parameters"]["UserId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Set a temporary password. The user must change it at next login. */
    post: operations["resetUserPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List own API tokens. Admins can list all tokens with all=true. */
    get: operations["listTokens"];
    put?: never;
    /** Create an API token. The secret is shown once. */
    post: operations["createToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tokens/{tokenId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tokenId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke an API token. Owners and admins can revoke. */
    delete: operations["revokeToken"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List audit events, newest first. */
    get: operations["listAuditEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/namespaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List namespaces with implicit parents. */
    get: operations["listNamespaces"];
    put?: never;
    /** Create a managed namespace. */
    post: operations["createNamespace"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/namespaces/{namespace}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    /** Get a namespace. */
    get: operations["getNamespace"];
    put?: never;
    post?: never;
    /** Delete a managed namespace. Fails with 409 while executions run. */
    delete: operations["deleteNamespace"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/namespaces/{namespace}/files": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    /** List the files of the head snapshot or of a version. */
    get: operations["listFiles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/namespaces/{namespace}/file": {
    parameters: {
      query: {
        /** @description File path relative to the namespace root. */
        path: components["parameters"]["FilePathQuery"];
      };
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    /** Download one file of the head snapshot or of a version. */
    get: operations["getFile"];
    /** Upload one file. This creates a new version. */
    put: operations["uploadFile"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/namespaces/{namespace}/changes": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create, update, rename and delete files in one new version. */
    post: operations["saveChanges"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/namespaces/{namespace}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    /** List versions (snapshots), newest first. */
    get: operations["listVersions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/namespaces/{namespace}/diff": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    /** Diff two versions. */
    get: operations["diffVersions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/namespaces/{namespace}/revert": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new version with the content of an old version. */
    post: operations["revertVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/namespaces/{namespace}/validate": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate proposed file content against the head snapshot. Nothing is saved. */
    post: operations["validateFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/flows": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List flows. */
    get: operations["listFlows"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/flows/{namespace}/{flowId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
      };
      cookie?: never;
    };
    /** Get a flow with its current revision and triggers. */
    get: operations["getFlow"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Enable or disable a flow. */
    patch: operations["updateFlow"];
    trace?: never;
  };
  "/api/v1/flows/{namespace}/{flowId}/revisions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
      };
      cookie?: never;
    };
    /** List revisions of a flow, newest first. */
    get: operations["listFlowRevisions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/flows/{namespace}/{flowId}/revisions/{revisionId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
        revisionId: string;
      };
      cookie?: never;
    };
    /** Get one revision with its source. */
    get: operations["getFlowRevision"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/flows/{namespace}/{flowId}/diff": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
      };
      cookie?: never;
    };
    /** Unified diff between two revisions of a flow. */
    get: operations["diffFlowRevisions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/flows/{namespace}/{flowId}/executions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a flow manually with inputs and labels. */
    post: operations["triggerFlow"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/namespaces/{namespace}/run": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run a script file of the namespace with optional args. */
    post: operations["runFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List executions with filters, sort and cursor pagination. */
    get: operations["listExecutions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    /** Get an execution with its task runs. */
    get: operations["getExecution"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel an execution. */
    post: operations["cancelExecution"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}/rerun": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a new execution with the same snapshot and inputs. */
    post: operations["rerunExecution"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}/restart": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a new execution that reuses the successful tasks and runs the others. */
    post: operations["restartExecution"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}/logs": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    /** Read log lines from Postgres or the archive. */
    get: operations["getExecutionLogs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}/logs/stream": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    /** Stream log lines as server-sent events. Supports Last-Event-ID. */
    get: operations["streamExecutionLogs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}/logs/download": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    /** Download all log lines as a text file. */
    get: operations["downloadExecutionLogs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}/events": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    /** Stream execution state changes as server-sent events. Supports Last-Event-ID. */
    get: operations["streamExecutionEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    /** List metrics emitted by the tasks. */
    get: operations["listExecutionMetrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}/artifacts": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    /** List artifacts uploaded by the tasks. */
    get: operations["listExecutionArtifacts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{executionId}/artifacts/{artifactId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
        artifactId: string;
      };
      cookie?: never;
    };
    /** Download an artifact. */
    get: operations["downloadArtifact"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/v1/task-runs/{taskRunId}/spec": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    /** Task spec with resolved env, mask values and limits. */
    get: operations["runnerGetSpec"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/v1/task-runs/{taskRunId}/bundle": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    /** Snapshot bundle (tar.gz). */
    get: operations["runnerGetBundle"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/v1/task-runs/{taskRunId}/logs": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ingest one log batch. Idempotent per (task run, seq). */
    post: operations["runnerPostLogs"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/v1/task-runs/{taskRunId}/events": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ingest outputs and metrics. */
    post: operations["runnerPostEvents"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/v1/task-runs/{taskRunId}/artifacts/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
        name: string;
      };
      cookie?: never;
    };
    get?: never;
    /** Upload one artifact as a streamed body. */
    put: operations["runnerPutArtifact"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/v1/task-runs/{taskRunId}/heartbeat": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Report liveness. The response says whether to cancel. */
    post: operations["runnerHeartbeat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/v1/task-runs/{taskRunId}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Report the end of the task. */
    post: operations["runnerComplete"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/schemas/flow.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** JSON Schema of flow files. */
    get: operations["getFlowSchema"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorEnvelope: {
      error: components["schemas"]["ErrorBody"];
    };
    ErrorBody: {
      code: string;
      message: string;
      details?: unknown;
    };
    CountResult: {
      count: number;
    };
    /** @enum {string} */
    Role: "viewer" | "operator" | "editor" | "admin";
    Instance: {
      /** Format: uuid */
      id: string;
      hostname: string;
      version: string;
      pools: string[];
      executors: string[];
      /** Format: date-time */
      started_at: string;
      /** Format: date-time */
      heartbeat_at: string;
      online: boolean;
    };
    InstanceList: {
      items: components["schemas"]["Instance"][];
    };
    LoginRequest: {
      email: string;
      password: string;
    };
    Me: {
      /** Format: uuid */
      id: string;
      email: string;
      name: string;
      role: components["schemas"]["Role"];
      must_change_password: boolean;
      /** @enum {string} */
      auth_type: "session" | "token";
    };
    UpdateMeRequest: {
      name: string;
    };
    ChangePasswordRequest: {
      current_password: string;
      new_password: string;
    };
    User: {
      /** Format: uuid */
      id: string;
      email: string;
      name: string;
      role: components["schemas"]["Role"];
      must_change_password: boolean;
      disabled: boolean;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      last_login_at?: string | null;
    };
    UserList: {
      items: components["schemas"]["User"][];
      next_cursor?: string;
    };
    CreateUserRequest: {
      /** Format: email */
      email: string;
      name?: string;
      role: components["schemas"]["Role"];
      /** @description Temporary password. The user must change it at first login. */
      password: string;
    };
    UpdateUserRequest: {
      name?: string;
      role?: components["schemas"]["Role"];
      disabled?: boolean;
    };
    ResetPasswordRequest: {
      password: string;
    };
    Token: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      user_id: string;
      user_email: string;
      name: string;
      prefix: string;
      role: components["schemas"]["Role"];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at?: string | null;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: date-time */
      revoked_at?: string | null;
    };
    TokenList: {
      items: components["schemas"]["Token"][];
      next_cursor?: string;
    };
    CreateTokenRequest: {
      name: string;
      role: components["schemas"]["Role"];
      expires_in_days?: number;
    };
    CreatedToken: {
      token: components["schemas"]["Token"];
      /** @description The token value. It is shown only once. */
      secret: string;
    };
    AuditEvent: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      ts: string;
      /** @enum {string} */
      actor_type: "user" | "token" | "system" | "ai";
      actor_id: string;
      actor_label: string;
      action: string;
      target_type: string;
      target_id: string;
      details: {
        [key: string]: unknown;
      };
      ip: string;
    };
    AuditList: {
      items: components["schemas"]["AuditEvent"][];
      next_cursor?: string;
    };
    Namespace: {
      name: string;
      /** @enum {string} */
      source_type: "managed" | "git" | "implicit";
      description: string;
      /** @description True for a parent that exists only because of its children. */
      implicit: boolean;
      parent?: string;
      head_version?: number | null;
      head_git_sha?: string;
      /** Format: uuid */
      git_source_id?: string | null;
      read_only?: boolean;
    };
    NamespaceList: {
      items: components["schemas"]["Namespace"][];
    };
    CreateNamespaceRequest: {
      name: string;
      description?: string;
    };
    FileEntry: {
      path: string;
      /** Format: int64 */
      size: number;
      hash: string;
      executable: boolean;
    };
    FileList: {
      version?: number | null;
      /** Format: uuid */
      snapshot_id?: string | null;
      git_sha?: string;
      items: components["schemas"]["FileEntry"][];
    };
    FileChange: {
      /** @enum {string} */
      op: "put" | "delete" | "rename";
      path: string;
      /** @description rename only. */
      new_path?: string;
      /** @description put only. UTF-8 text content. */
      content?: string;
      /** @description put only. Binary content as base64. Used instead of content. */
      content_base64?: string;
      executable?: boolean;
    };
    SaveChangesRequest: {
      message: string;
      /** @description Fails with 409 version_conflict when the head version differs. */
      base_version?: number;
      changes: components["schemas"]["FileChange"][];
    };
    Snapshot: {
      /** Format: uuid */
      id: string;
      version?: number | null;
      git_sha?: string;
      message: string;
      author: string;
      /** Format: date-time */
      created_at: string;
      manifest_hash: string;
      file_count: number;
    };
    SnapshotList: {
      items: components["schemas"]["Snapshot"][];
    };
    FileDiff: {
      path: string;
      /** @enum {string} */
      status: "added" | "removed" | "modified";
      binary: boolean;
      /** @description Unified diff for text files. */
      diff: string;
    };
    VersionDiff: {
      from: number;
      to: number;
      files: components["schemas"]["FileDiff"][];
    };
    RevertRequest: {
      version: number;
      message?: string;
    };
    Issue: {
      code: string;
      path: string;
      line: number;
      column: number;
      message: string;
    };
    ValidateFileRequest: {
      path: string;
      content: string;
    };
    ValidateFileResult: {
      valid: boolean;
      /** @enum {string} */
      kind: "flow" | "namespace" | "other";
      flow_id?: string;
      errors: components["schemas"]["Issue"][];
    };
    ExecutionRef: {
      /** Format: uuid */
      id: string;
      state: string;
      /** Format: date-time */
      created_at: string;
    };
    FlowSummary: {
      /** Format: uuid */
      id: string;
      namespace: string;
      flow_id: string;
      path: string;
      valid: boolean;
      disabled: boolean;
      description: string;
      error_count: number;
      labels?: {
        [key: string]: string;
      };
      last_execution?: components["schemas"]["ExecutionRef"];
    };
    FlowList: {
      items: components["schemas"]["FlowSummary"][];
      next_cursor?: string;
    };
    TriggerInfo: {
      key: string;
      /** @enum {string} */
      type: "schedule" | "webhook" | "flow";
      active: boolean;
      config: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      next_fire_at?: string | null;
      /** Format: date-time */
      last_fired_at?: string | null;
      has_webhook_key: boolean;
    };
    Revision: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      created_at: string;
      snapshot_version?: number | null;
      git_sha?: string;
      message?: string;
      path: string;
      source: string;
      valid: boolean;
      definition?: {
        [key: string]: unknown;
      } | null;
      errors: components["schemas"]["Issue"][];
    };
    RevisionSummary: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      created_at: string;
      snapshot_version?: number | null;
      git_sha?: string;
      message?: string;
      valid: boolean;
      error_count: number;
    };
    RevisionList: {
      items: components["schemas"]["RevisionSummary"][];
    };
    FlowDetail: components["schemas"]["FlowSummary"] & {
      revision?: components["schemas"]["Revision"];
      triggers: components["schemas"]["TriggerInfo"][];
    };
    UpdateFlowRequest: {
      disabled: boolean;
    };
    TextDiff: {
      diff: string;
    };
    TriggerRequest: {
      inputs?: {
        [key: string]: unknown;
      };
      labels?: {
        [key: string]: string;
      };
    };
    RunFileRequest: {
      path: string;
      args?: string[];
    };
    /** @enum {string} */
    ExecutionState:
      | "QUEUED"
      | "RUNNING"
      | "CANCELLING"
      | "SUCCESS"
      | "FAILED"
      | "TIMED_OUT"
      | "CANCELLED"
      | "SKIPPED";
    /** @enum {string} */
    TaskRunState:
      | "PENDING"
      | "QUEUED"
      | "RUNNING"
      | "SUCCESS"
      | "FAILED"
      | "TIMED_OUT"
      | "CANCELLED"
      | "SKIPPED";
    ExecutionSummary: {
      /** Format: uuid */
      id: string;
      namespace: string;
      /** @description Flow ID. Null for file runs. */
      flow_id?: string | null;
      state: components["schemas"]["ExecutionState"];
      trigger_type: string;
      labels: {
        [key: string]: string;
      };
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      started_at?: string | null;
      /** Format: date-time */
      ended_at?: string | null;
      /** Format: int64 */
      duration_ms?: number | null;
      error: string;
      reason: string;
      created_by: string;
    };
    ExecutionList: {
      items: components["schemas"]["ExecutionSummary"][];
      next_cursor?: string;
    };
    TaskRun: {
      /** Format: uuid */
      id: string;
      task_key: string;
      task_type: string;
      attempt: number;
      state: components["schemas"]["TaskRunState"];
      reason: string;
      executor_type: string;
      pool: string;
      /** Format: date-time */
      queued_at?: string | null;
      /** Format: date-time */
      started_at?: string | null;
      /** Format: date-time */
      ended_at?: string | null;
      /** Format: int64 */
      duration_ms?: number | null;
      exit_code?: number | null;
      error: string;
      outputs?: {
        [key: string]: unknown;
      } | null;
      /** Format: uuid */
      reused_from_id?: string | null;
      /** Format: uuid */
      child_execution_id?: string | null;
    };
    ExecutionDetail: components["schemas"]["ExecutionSummary"] & {
      inputs: {
        [key: string]: unknown;
      };
      outputs?: {
        [key: string]: unknown;
      } | null;
      trigger_payload: {
        [key: string]: unknown;
      };
      /** Format: uuid */
      snapshot_id: string;
      snapshot_version?: number | null;
      git_sha?: string;
      /** Format: uuid */
      flow_revision_id?: string | null;
      /** Format: uuid */
      parent_execution_id?: string | null;
      /** Format: uuid */
      restart_of_id?: string | null;
      chain_depth: number;
      secret_keys_used: string[];
      task_runs: components["schemas"]["TaskRun"][];
      children: components["schemas"]["ExecutionRef"][];
    };
    LogEntry: {
      /** Format: uuid */
      task_run_id: string;
      task_key: string;
      attempt: number;
      /**
       * Format: int64
       * @description 1-based line number in the task run.
       */
      n: number;
      /** Format: date-time */
      ts: string;
      /** @enum {string} */
      stream: "stdout" | "stderr" | "system";
      text: string;
    };
    LogPage: {
      lines: components["schemas"]["LogEntry"][];
      next_cursor?: string;
      /** @description True when the execution ended and no more lines follow. */
      done: boolean;
    };
    MetricPoint: {
      /** Format: uuid */
      task_run_id: string;
      task_key: string;
      name: string;
      /** Format: double */
      value: number;
      unit: string;
      tags: {
        [key: string]: string;
      };
      /** Format: date-time */
      ts: string;
    };
    MetricList: {
      items: components["schemas"]["MetricPoint"][];
    };
    Artifact: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      task_run_id: string;
      task_key: string;
      name: string;
      /** Format: int64 */
      size: number;
      content_type: string;
      /** Format: date-time */
      created_at: string;
    };
    ArtifactList: {
      items: components["schemas"]["Artifact"][];
    };
    RunnerLimits: {
      /** Format: int64 */
      max_artifact_bytes: number;
      /** Format: int64 */
      max_bundle_bytes: number;
    };
    RunnerSpec: {
      task_run_id: string;
      execution_id: string;
      namespace: string;
      flow_id: string;
      task_id: string;
      attempt: number;
      command: string[];
      workdir: string;
      env: {
        [key: string]: string;
      };
      runtime?: string;
      timeout_seconds: number;
      mask_values: string[];
      bundle_hash: string;
      limits: components["schemas"]["RunnerLimits"];
    };
    RunnerLogLine: {
      /** Format: date-time */
      ts: string;
      /** @enum {string} */
      stream: "stdout" | "stderr" | "system";
      text: string;
    };
    RunnerLogBatch: {
      seq: number;
      lines: components["schemas"]["RunnerLogLine"][];
    };
    RunnerEvent: {
      /** @enum {string} */
      type: "output" | "metric";
      key?: string;
      value?: unknown;
      name?: string;
      unit?: string;
      tags?: {
        [key: string]: string;
      };
      /** Format: date-time */
      ts?: string;
    };
    RunnerEventBatch: {
      seq: number;
      events: components["schemas"]["RunnerEvent"][];
    };
    RunnerHeartbeatResponse: {
      cancel: boolean;
    };
    RunnerComplete: {
      exit_code: number;
      error: string;
      reason?: string;
    };
  };
  responses: {
    /** @description Error envelope. */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
  };
  parameters: {
    ExecutionIdPath: string;
    TaskRunIdPath: string;
    /** @description Opaque cursor from next_cursor of the previous page. */
    Cursor: string;
    Limit: number;
    UserId: string;
    NamespacePath: string;
    FlowIdPath: string;
    /** @description File path relative to the namespace root. */
    FilePathQuery: string;
    /** @description Version number. Default is the head version. */
    VersionQuery: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listInstances: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Instances. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InstanceList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Signed in. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  updateMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMeRequest"];
      };
    };
    responses: {
      /** @description Updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Changed. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  revokeOtherSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Other sessions deleted. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CountResult"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listUsers: {
    parameters: {
      query?: {
        /** @description Opaque cursor from next_cursor of the previous page. */
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Users. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
    responses: {
      /** @description Created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: components["parameters"]["UserId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"];
      };
    };
    responses: {
      /** @description Updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  resetUserPassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: components["parameters"]["UserId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Reset. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  listTokens: {
    parameters: {
      query?: {
        all?: boolean;
        /** @description Opaque cursor from next_cursor of the previous page. */
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tokens. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  createToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTokenRequest"];
      };
    };
    responses: {
      /** @description Created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedToken"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  revokeToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tokenId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  listAuditEvents: {
    parameters: {
      query?: {
        /** @description Actor ID or email. */
        actor?: string;
        action?: string;
        /** @description Target type, or type:id. */
        target?: string;
        from?: string;
        to?: string;
        /** @description Opaque cursor from next_cursor of the previous page. */
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Audit events. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listNamespaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Namespaces in name order. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NamespaceList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  createNamespace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateNamespaceRequest"];
      };
    };
    responses: {
      /** @description Created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Namespace"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getNamespace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Namespace. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Namespace"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  deleteNamespace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  listFiles: {
    parameters: {
      query?: {
        /** @description Version number. Default is the head version. */
        version?: components["parameters"]["VersionQuery"];
      };
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Files. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getFile: {
    parameters: {
      query: {
        /** @description File path relative to the namespace root. */
        path: components["parameters"]["FilePathQuery"];
        /** @description Version number. Default is the head version. */
        version?: components["parameters"]["VersionQuery"];
      };
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File content. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      default: components["responses"]["Error"];
    };
  };
  uploadFile: {
    parameters: {
      query: {
        /** @description File path relative to the namespace root. */
        path: components["parameters"]["FilePathQuery"];
        message?: string;
        executable?: boolean;
      };
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": string;
      };
    };
    responses: {
      /** @description New version. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Snapshot"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  saveChanges: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveChangesRequest"];
      };
    };
    responses: {
      /** @description New version. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Snapshot"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listVersions: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Versions. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnapshotList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  diffVersions: {
    parameters: {
      query: {
        from: number;
        to: number;
      };
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diff. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionDiff"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  revertVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevertRequest"];
      };
    };
    responses: {
      /** @description New version. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Snapshot"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  validateFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidateFileRequest"];
      };
    };
    responses: {
      /** @description Validation result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidateFileResult"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listFlows: {
    parameters: {
      query?: {
        /** @description Namespace and its children. */
        namespace?: string;
        /** @description Opaque cursor from next_cursor of the previous page. */
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Flows. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlowList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Flow. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlowDetail"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  updateFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateFlowRequest"];
      };
    };
    responses: {
      /** @description Updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlowDetail"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listFlowRevisions: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revisions. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevisionList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getFlowRevision: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
        revisionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revision. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Revision"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  diffFlowRevisions: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diff. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TextDiff"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  triggerFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
        flowId: components["parameters"]["FlowIdPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TriggerRequest"];
      };
    };
    responses: {
      /** @description Execution created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionDetail"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  runFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        namespace: components["parameters"]["NamespacePath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunFileRequest"];
      };
    };
    responses: {
      /** @description Execution created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionDetail"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listExecutions: {
    parameters: {
      query?: {
        /** @description Comma-separated execution states. */
        state?: string;
        /** @description Namespace and its children. */
        namespace?: string;
        /** @description Flow as <namespace>/<flow_id>. */
        flow?: string;
        trigger_type?:
          | "manual"
          | "schedule"
          | "webhook"
          | "flow"
          | "file"
          | "subflow"
          | "rerun"
          | "restart";
        /** @description Label filter key=value. Repeat for several labels. */
        label?: string[];
        from?: string;
        to?: string;
        sort?: "created" | "duration";
        /** @description Opaque cursor from next_cursor of the previous page. */
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Executions. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getExecution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Execution. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionDetail"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  cancelExecution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancel requested. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionDetail"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  rerunExecution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Execution created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionDetail"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  restartExecution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Execution created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionDetail"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getExecutionLogs: {
    parameters: {
      query?: {
        /** @description Task ID filter. */
        task?: string;
        /** @description Case-insensitive text filter. */
        search?: string;
        /** @description Opaque cursor from next_cursor of the previous page. */
        cursor?: components["parameters"]["Cursor"];
        limit?: number;
      };
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Log lines. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogPage"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  streamExecutionLogs: {
    parameters: {
      query?: {
        task?: string;
      };
      header?: {
        "Last-Event-ID"?: string;
      };
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Event stream. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
      default: components["responses"]["Error"];
    };
  };
  downloadExecutionLogs: {
    parameters: {
      query?: {
        task?: string;
      };
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Log file. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      default: components["responses"]["Error"];
    };
  };
  streamExecutionEvents: {
    parameters: {
      query?: never;
      header?: {
        "Last-Event-ID"?: string;
      };
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Event stream. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listExecutionMetrics: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Metrics. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetricList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listExecutionArtifacts: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Artifacts. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtifactList"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  downloadArtifact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionIdPath"];
        artifactId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Artifact content. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      default: components["responses"]["Error"];
    };
  };
  runnerGetSpec: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Spec. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunnerSpec"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  runnerGetBundle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bundle. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/gzip": string;
        };
      };
      default: components["responses"]["Error"];
    };
  };
  runnerPostLogs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunnerLogBatch"];
      };
    };
    responses: {
      /** @description Stored. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  runnerPostEvents: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunnerEventBatch"];
      };
    };
    responses: {
      /** @description Stored. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  runnerPutArtifact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": string;
      };
    };
    responses: {
      /** @description Stored. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  runnerHeartbeat: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Heartbeat response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunnerHeartbeatResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  runnerComplete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskRunId: components["parameters"]["TaskRunIdPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunnerComplete"];
      };
    };
    responses: {
      /** @description Recorded. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  getFlowSchema: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON Schema. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      default: components["responses"]["Error"];
    };
  };
}
