// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  ServerSentEventsResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  CancelExecutionData,
  CancelExecutionErrors,
  CancelExecutionResponses,
  ChangePasswordData,
  ChangePasswordErrors,
  ChangePasswordResponses,
  CheckGlobalSecretData,
  CheckGlobalSecretErrors,
  CheckGlobalSecretResponses,
  CheckNamespaceSecretData,
  CheckNamespaceSecretErrors,
  CheckNamespaceSecretResponses,
  CheckSecretProviderData,
  CheckSecretProviderErrors,
  CheckSecretProviderResponses,
  CreateNamespaceData,
  CreateNamespaceErrors,
  CreateNamespaceResponses,
  CreateSecretProviderData,
  CreateSecretProviderErrors,
  CreateSecretProviderResponses,
  CreateTokenData,
  CreateTokenErrors,
  CreateTokenResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteGlobalSecretData,
  DeleteGlobalSecretErrors,
  DeleteGlobalSecretResponses,
  DeleteGlobalVariableData,
  DeleteGlobalVariableErrors,
  DeleteGlobalVariableResponses,
  DeleteNamespaceData,
  DeleteNamespaceErrors,
  DeleteNamespaceResponses,
  DeleteNamespaceSecretData,
  DeleteNamespaceSecretErrors,
  DeleteNamespaceSecretResponses,
  DeleteNamespaceVariableData,
  DeleteNamespaceVariableErrors,
  DeleteNamespaceVariableResponses,
  DeleteSecretProviderData,
  DeleteSecretProviderErrors,
  DeleteSecretProviderResponses,
  DiffFlowRevisionsData,
  DiffFlowRevisionsErrors,
  DiffFlowRevisionsResponses,
  DiffVersionsData,
  DiffVersionsErrors,
  DiffVersionsResponses,
  DownloadArtifactData,
  DownloadArtifactResponses,
  DownloadExecutionLogsData,
  DownloadExecutionLogsResponses,
  FireWebhookData,
  FireWebhookResponses,
  GetExecutionData,
  GetExecutionErrors,
  GetExecutionLogsData,
  GetExecutionLogsErrors,
  GetExecutionLogsResponses,
  GetExecutionResponses,
  GetFileData,
  GetFileResponses,
  GetFlowData,
  GetFlowErrors,
  GetFlowResponses,
  GetFlowRevisionData,
  GetFlowRevisionErrors,
  GetFlowRevisionResponses,
  GetFlowSchemaData,
  GetFlowSchemaErrors,
  GetFlowSchemaResponses,
  GetMeData,
  GetMeErrors,
  GetMeResponses,
  GetNamespaceData,
  GetNamespaceErrors,
  GetNamespaceResponses,
  ListAuditEventsData,
  ListAuditEventsErrors,
  ListAuditEventsResponses,
  ListExecutionArtifactsData,
  ListExecutionArtifactsErrors,
  ListExecutionArtifactsResponses,
  ListExecutionMetricsData,
  ListExecutionMetricsErrors,
  ListExecutionMetricsResponses,
  ListExecutionsData,
  ListExecutionsErrors,
  ListExecutionsResponses,
  ListFilesData,
  ListFilesErrors,
  ListFilesResponses,
  ListFlowRevisionsData,
  ListFlowRevisionsErrors,
  ListFlowRevisionsResponses,
  ListFlowsData,
  ListFlowsErrors,
  ListFlowsResponses,
  ListGlobalSecretsData,
  ListGlobalSecretsErrors,
  ListGlobalSecretsResponses,
  ListGlobalVariablesData,
  ListGlobalVariablesErrors,
  ListGlobalVariablesResponses,
  ListInstancesData,
  ListInstancesErrors,
  ListInstancesResponses,
  ListNamespacesData,
  ListNamespaceSecretsData,
  ListNamespaceSecretsErrors,
  ListNamespaceSecretsResponses,
  ListNamespacesErrors,
  ListNamespacesResponses,
  ListNamespaceVariablesData,
  ListNamespaceVariablesErrors,
  ListNamespaceVariablesResponses,
  ListSecretProvidersData,
  ListSecretProvidersErrors,
  ListSecretProvidersResponses,
  ListTokensData,
  ListTokensErrors,
  ListTokensResponses,
  ListUpcomingSchedulesData,
  ListUpcomingSchedulesErrors,
  ListUpcomingSchedulesResponses,
  ListUsersData,
  ListUsersErrors,
  ListUsersResponses,
  ListVersionsData,
  ListVersionsErrors,
  ListVersionsResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  LogoutData,
  LogoutErrors,
  LogoutResponses,
  PutGlobalSecretData,
  PutGlobalSecretErrors,
  PutGlobalSecretResponses,
  PutGlobalVariableData,
  PutGlobalVariableErrors,
  PutGlobalVariableResponses,
  PutNamespaceSecretData,
  PutNamespaceSecretErrors,
  PutNamespaceSecretResponses,
  PutNamespaceVariableData,
  PutNamespaceVariableErrors,
  PutNamespaceVariableResponses,
  RerunExecutionData,
  RerunExecutionErrors,
  RerunExecutionResponses,
  ResetUserPasswordData,
  ResetUserPasswordErrors,
  ResetUserPasswordResponses,
  RestartExecutionData,
  RestartExecutionErrors,
  RestartExecutionResponses,
  RevertVersionData,
  RevertVersionErrors,
  RevertVersionResponses,
  RevokeOtherSessionsData,
  RevokeOtherSessionsErrors,
  RevokeOtherSessionsResponses,
  RevokeTokenData,
  RevokeTokenErrors,
  RevokeTokenResponses,
  RotateWebhookKeyData,
  RotateWebhookKeyErrors,
  RotateWebhookKeyResponses,
  RunFileData,
  RunFileErrors,
  RunFileResponses,
  RunnerCompleteData,
  RunnerCompleteErrors,
  RunnerCompleteResponses,
  RunnerGetBundleData,
  RunnerGetBundleResponses,
  RunnerGetSpecData,
  RunnerGetSpecErrors,
  RunnerGetSpecResponses,
  RunnerHeartbeatData,
  RunnerHeartbeatErrors,
  RunnerHeartbeatResponses,
  RunnerPostEventsData,
  RunnerPostEventsErrors,
  RunnerPostEventsResponses,
  RunnerPostLogsData,
  RunnerPostLogsErrors,
  RunnerPostLogsResponses,
  RunnerPutArtifactData,
  RunnerPutArtifactResponses,
  SaveChangesData,
  SaveChangesErrors,
  SaveChangesResponses,
  StreamExecutionEventsData,
  StreamExecutionEventsResponses,
  StreamExecutionLogsData,
  StreamExecutionLogsResponses,
  TriggerFlowData,
  TriggerFlowErrors,
  TriggerFlowResponses,
  UpdateFlowData,
  UpdateFlowErrors,
  UpdateFlowResponses,
  UpdateMeData,
  UpdateMeErrors,
  UpdateMeResponses,
  UpdateSecretProviderData,
  UpdateSecretProviderErrors,
  UpdateSecretProviderResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
  UploadFileData,
  UploadFileResponses,
  ValidateFileData,
  ValidateFileErrors,
  ValidateFileResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const runnerPutArtifact = <ThrowOnError extends boolean = false>(
  options: Options<RunnerPutArtifactData, ThrowOnError>,
): RequestResult<RunnerPutArtifactResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<
    RunnerPutArtifactResponses,
    unknown,
    ThrowOnError
  >({
    bodySerializer: null,
    url: "/api/runner/v1/task-runs/{taskRunId}/artifacts/{name}",
    ...options,
    headers: {
      "Content-Type": "application/octet-stream",
      ...options.headers,
    },
  });

export const runnerGetBundle = <ThrowOnError extends boolean = false>(
  options: Options<RunnerGetBundleData, ThrowOnError>,
): RequestResult<RunnerGetBundleResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    RunnerGetBundleResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/runner/v1/task-runs/{taskRunId}/bundle", ...options });

export const runnerComplete = <ThrowOnError extends boolean = false>(
  options: Options<RunnerCompleteData, ThrowOnError>,
): RequestResult<RunnerCompleteResponses, RunnerCompleteErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RunnerCompleteResponses,
    RunnerCompleteErrors,
    ThrowOnError
  >({
    url: "/api/runner/v1/task-runs/{taskRunId}/complete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const runnerPostEvents = <ThrowOnError extends boolean = false>(
  options: Options<RunnerPostEventsData, ThrowOnError>,
): RequestResult<
  RunnerPostEventsResponses,
  RunnerPostEventsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RunnerPostEventsResponses,
    RunnerPostEventsErrors,
    ThrowOnError
  >({
    url: "/api/runner/v1/task-runs/{taskRunId}/events",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const runnerHeartbeat = <ThrowOnError extends boolean = false>(
  options: Options<RunnerHeartbeatData, ThrowOnError>,
): RequestResult<
  RunnerHeartbeatResponses,
  RunnerHeartbeatErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RunnerHeartbeatResponses,
    RunnerHeartbeatErrors,
    ThrowOnError
  >({ url: "/api/runner/v1/task-runs/{taskRunId}/heartbeat", ...options });

export const runnerPostLogs = <ThrowOnError extends boolean = false>(
  options: Options<RunnerPostLogsData, ThrowOnError>,
): RequestResult<RunnerPostLogsResponses, RunnerPostLogsErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RunnerPostLogsResponses,
    RunnerPostLogsErrors,
    ThrowOnError
  >({
    url: "/api/runner/v1/task-runs/{taskRunId}/logs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const runnerGetSpec = <ThrowOnError extends boolean = false>(
  options: Options<RunnerGetSpecData, ThrowOnError>,
): RequestResult<RunnerGetSpecResponses, RunnerGetSpecErrors, ThrowOnError> =>
  (options.client ?? client).get<
    RunnerGetSpecResponses,
    RunnerGetSpecErrors,
    ThrowOnError
  >({ url: "/api/runner/v1/task-runs/{taskRunId}/spec", ...options });

export const listAuditEvents = <ThrowOnError extends boolean = false>(
  options?: Options<ListAuditEventsData, ThrowOnError>,
): RequestResult<
  ListAuditEventsResponses,
  ListAuditEventsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListAuditEventsResponses,
    ListAuditEventsErrors,
    ThrowOnError
  >({ url: "/api/v1/audit", ...options });

export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
): RequestResult<LoginResponses, LoginErrors, ThrowOnError> =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: "/api/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>(
    { url: "/api/v1/auth/logout", ...options },
  );

export const getMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetMeData, ThrowOnError>,
): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    url: "/api/v1/auth/me",
    ...options,
  });

export const updateMe = <ThrowOnError extends boolean = false>(
  options: Options<UpdateMeData, ThrowOnError>,
): RequestResult<UpdateMeResponses, UpdateMeErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    UpdateMeResponses,
    UpdateMeErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const changePassword = <ThrowOnError extends boolean = false>(
  options: Options<ChangePasswordData, ThrowOnError>,
): RequestResult<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ChangePasswordResponses,
    ChangePasswordErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const revokeOtherSessions = <ThrowOnError extends boolean = false>(
  options?: Options<RevokeOtherSessionsData, ThrowOnError>,
): RequestResult<
  RevokeOtherSessionsResponses,
  RevokeOtherSessionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    RevokeOtherSessionsResponses,
    RevokeOtherSessionsErrors,
    ThrowOnError
  >({ url: "/api/v1/auth/sessions/revoke-others", ...options });

export const listExecutions = <ThrowOnError extends boolean = false>(
  options?: Options<ListExecutionsData, ThrowOnError>,
): RequestResult<ListExecutionsResponses, ListExecutionsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListExecutionsResponses,
    ListExecutionsErrors,
    ThrowOnError
  >({ url: "/api/v1/executions", ...options });

export const getExecution = <ThrowOnError extends boolean = false>(
  options: Options<GetExecutionData, ThrowOnError>,
): RequestResult<GetExecutionResponses, GetExecutionErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetExecutionResponses,
    GetExecutionErrors,
    ThrowOnError
  >({ url: "/api/v1/executions/{executionId}", ...options });

export const listExecutionArtifacts = <ThrowOnError extends boolean = false>(
  options: Options<ListExecutionArtifactsData, ThrowOnError>,
): RequestResult<
  ListExecutionArtifactsResponses,
  ListExecutionArtifactsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListExecutionArtifactsResponses,
    ListExecutionArtifactsErrors,
    ThrowOnError
  >({ url: "/api/v1/executions/{executionId}/artifacts", ...options });

export const downloadArtifact = <ThrowOnError extends boolean = false>(
  options: Options<DownloadArtifactData, ThrowOnError>,
): RequestResult<DownloadArtifactResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    DownloadArtifactResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/executions/{executionId}/artifacts/{artifactId}",
    ...options,
  });

export const cancelExecution = <ThrowOnError extends boolean = false>(
  options: Options<CancelExecutionData, ThrowOnError>,
): RequestResult<
  CancelExecutionResponses,
  CancelExecutionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CancelExecutionResponses,
    CancelExecutionErrors,
    ThrowOnError
  >({ url: "/api/v1/executions/{executionId}/cancel", ...options });

export const streamExecutionEvents = <ThrowOnError extends boolean = false>(
  options: Options<StreamExecutionEventsData, ThrowOnError, unknown>,
): Promise<ServerSentEventsResult<StreamExecutionEventsResponses>> =>
  (options.client ?? client).sse.get<
    StreamExecutionEventsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/executions/{executionId}/events", ...options });

export const getExecutionLogs = <ThrowOnError extends boolean = false>(
  options: Options<GetExecutionLogsData, ThrowOnError>,
): RequestResult<
  GetExecutionLogsResponses,
  GetExecutionLogsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetExecutionLogsResponses,
    GetExecutionLogsErrors,
    ThrowOnError
  >({ url: "/api/v1/executions/{executionId}/logs", ...options });

export const downloadExecutionLogs = <ThrowOnError extends boolean = false>(
  options: Options<DownloadExecutionLogsData, ThrowOnError>,
): RequestResult<DownloadExecutionLogsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    DownloadExecutionLogsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/executions/{executionId}/logs/download", ...options });

export const streamExecutionLogs = <ThrowOnError extends boolean = false>(
  options: Options<StreamExecutionLogsData, ThrowOnError, unknown>,
): Promise<ServerSentEventsResult<StreamExecutionLogsResponses>> =>
  (options.client ?? client).sse.get<
    StreamExecutionLogsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/executions/{executionId}/logs/stream", ...options });

export const listExecutionMetrics = <ThrowOnError extends boolean = false>(
  options: Options<ListExecutionMetricsData, ThrowOnError>,
): RequestResult<
  ListExecutionMetricsResponses,
  ListExecutionMetricsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListExecutionMetricsResponses,
    ListExecutionMetricsErrors,
    ThrowOnError
  >({ url: "/api/v1/executions/{executionId}/metrics", ...options });

export const rerunExecution = <ThrowOnError extends boolean = false>(
  options: Options<RerunExecutionData, ThrowOnError>,
): RequestResult<RerunExecutionResponses, RerunExecutionErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RerunExecutionResponses,
    RerunExecutionErrors,
    ThrowOnError
  >({ url: "/api/v1/executions/{executionId}/rerun", ...options });

export const restartExecution = <ThrowOnError extends boolean = false>(
  options: Options<RestartExecutionData, ThrowOnError>,
): RequestResult<
  RestartExecutionResponses,
  RestartExecutionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RestartExecutionResponses,
    RestartExecutionErrors,
    ThrowOnError
  >({ url: "/api/v1/executions/{executionId}/restart", ...options });

export const listFlows = <ThrowOnError extends boolean = false>(
  options?: Options<ListFlowsData, ThrowOnError>,
): RequestResult<ListFlowsResponses, ListFlowsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListFlowsResponses,
    ListFlowsErrors,
    ThrowOnError
  >({ url: "/api/v1/flows", ...options });

export const getFlow = <ThrowOnError extends boolean = false>(
  options: Options<GetFlowData, ThrowOnError>,
): RequestResult<GetFlowResponses, GetFlowErrors, ThrowOnError> =>
  (options.client ?? client).get<GetFlowResponses, GetFlowErrors, ThrowOnError>(
    { url: "/api/v1/flows/{namespace}/{flowId}", ...options },
  );

export const updateFlow = <ThrowOnError extends boolean = false>(
  options: Options<UpdateFlowData, ThrowOnError>,
): RequestResult<UpdateFlowResponses, UpdateFlowErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    UpdateFlowResponses,
    UpdateFlowErrors,
    ThrowOnError
  >({
    url: "/api/v1/flows/{namespace}/{flowId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const diffFlowRevisions = <ThrowOnError extends boolean = false>(
  options: Options<DiffFlowRevisionsData, ThrowOnError>,
): RequestResult<
  DiffFlowRevisionsResponses,
  DiffFlowRevisionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    DiffFlowRevisionsResponses,
    DiffFlowRevisionsErrors,
    ThrowOnError
  >({ url: "/api/v1/flows/{namespace}/{flowId}/diff", ...options });

export const triggerFlow = <ThrowOnError extends boolean = false>(
  options: Options<TriggerFlowData, ThrowOnError>,
): RequestResult<TriggerFlowResponses, TriggerFlowErrors, ThrowOnError> =>
  (options.client ?? client).post<
    TriggerFlowResponses,
    TriggerFlowErrors,
    ThrowOnError
  >({
    url: "/api/v1/flows/{namespace}/{flowId}/executions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const listFlowRevisions = <ThrowOnError extends boolean = false>(
  options: Options<ListFlowRevisionsData, ThrowOnError>,
): RequestResult<
  ListFlowRevisionsResponses,
  ListFlowRevisionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListFlowRevisionsResponses,
    ListFlowRevisionsErrors,
    ThrowOnError
  >({ url: "/api/v1/flows/{namespace}/{flowId}/revisions", ...options });

export const getFlowRevision = <ThrowOnError extends boolean = false>(
  options: Options<GetFlowRevisionData, ThrowOnError>,
): RequestResult<
  GetFlowRevisionResponses,
  GetFlowRevisionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetFlowRevisionResponses,
    GetFlowRevisionErrors,
    ThrowOnError
  >({
    url: "/api/v1/flows/{namespace}/{flowId}/revisions/{revisionId}",
    ...options,
  });

export const rotateWebhookKey = <ThrowOnError extends boolean = false>(
  options: Options<RotateWebhookKeyData, ThrowOnError>,
): RequestResult<
  RotateWebhookKeyResponses,
  RotateWebhookKeyErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RotateWebhookKeyResponses,
    RotateWebhookKeyErrors,
    ThrowOnError
  >({
    url: "/api/v1/flows/{namespace}/{flowId}/triggers/{triggerId}/webhook-key",
    ...options,
  });

export const listInstances = <ThrowOnError extends boolean = false>(
  options?: Options<ListInstancesData, ThrowOnError>,
): RequestResult<ListInstancesResponses, ListInstancesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListInstancesResponses,
    ListInstancesErrors,
    ThrowOnError
  >({ url: "/api/v1/instances", ...options });

export const listNamespaces = <ThrowOnError extends boolean = false>(
  options?: Options<ListNamespacesData, ThrowOnError>,
): RequestResult<ListNamespacesResponses, ListNamespacesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListNamespacesResponses,
    ListNamespacesErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces", ...options });

export const createNamespace = <ThrowOnError extends boolean = false>(
  options: Options<CreateNamespaceData, ThrowOnError>,
): RequestResult<
  CreateNamespaceResponses,
  CreateNamespaceErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateNamespaceResponses,
    CreateNamespaceErrors,
    ThrowOnError
  >({
    url: "/api/v1/namespaces",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deleteNamespace = <ThrowOnError extends boolean = false>(
  options: Options<DeleteNamespaceData, ThrowOnError>,
): RequestResult<
  DeleteNamespaceResponses,
  DeleteNamespaceErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteNamespaceResponses,
    DeleteNamespaceErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces/{namespace}", ...options });

export const getNamespace = <ThrowOnError extends boolean = false>(
  options: Options<GetNamespaceData, ThrowOnError>,
): RequestResult<GetNamespaceResponses, GetNamespaceErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetNamespaceResponses,
    GetNamespaceErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces/{namespace}", ...options });

export const saveChanges = <ThrowOnError extends boolean = false>(
  options: Options<SaveChangesData, ThrowOnError>,
): RequestResult<SaveChangesResponses, SaveChangesErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SaveChangesResponses,
    SaveChangesErrors,
    ThrowOnError
  >({
    url: "/api/v1/namespaces/{namespace}/changes",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const diffVersions = <ThrowOnError extends boolean = false>(
  options: Options<DiffVersionsData, ThrowOnError>,
): RequestResult<DiffVersionsResponses, DiffVersionsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    DiffVersionsResponses,
    DiffVersionsErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces/{namespace}/diff", ...options });

export const getFile = <ThrowOnError extends boolean = false>(
  options: Options<GetFileData, ThrowOnError>,
): RequestResult<GetFileResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetFileResponses, unknown, ThrowOnError>({
    url: "/api/v1/namespaces/{namespace}/file",
    ...options,
  });

export const uploadFile = <ThrowOnError extends boolean = false>(
  options: Options<UploadFileData, ThrowOnError>,
): RequestResult<UploadFileResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<UploadFileResponses, unknown, ThrowOnError>({
    bodySerializer: null,
    url: "/api/v1/namespaces/{namespace}/file",
    ...options,
    headers: {
      "Content-Type": "application/octet-stream",
      ...options.headers,
    },
  });

export const listFiles = <ThrowOnError extends boolean = false>(
  options: Options<ListFilesData, ThrowOnError>,
): RequestResult<ListFilesResponses, ListFilesErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListFilesResponses,
    ListFilesErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces/{namespace}/files", ...options });

export const revertVersion = <ThrowOnError extends boolean = false>(
  options: Options<RevertVersionData, ThrowOnError>,
): RequestResult<RevertVersionResponses, RevertVersionErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RevertVersionResponses,
    RevertVersionErrors,
    ThrowOnError
  >({
    url: "/api/v1/namespaces/{namespace}/revert",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const runFile = <ThrowOnError extends boolean = false>(
  options: Options<RunFileData, ThrowOnError>,
): RequestResult<RunFileResponses, RunFileErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RunFileResponses,
    RunFileErrors,
    ThrowOnError
  >({
    url: "/api/v1/namespaces/{namespace}/run",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const listNamespaceSecrets = <ThrowOnError extends boolean = false>(
  options: Options<ListNamespaceSecretsData, ThrowOnError>,
): RequestResult<
  ListNamespaceSecretsResponses,
  ListNamespaceSecretsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListNamespaceSecretsResponses,
    ListNamespaceSecretsErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces/{namespace}/secrets", ...options });

export const deleteNamespaceSecret = <ThrowOnError extends boolean = false>(
  options: Options<DeleteNamespaceSecretData, ThrowOnError>,
): RequestResult<
  DeleteNamespaceSecretResponses,
  DeleteNamespaceSecretErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteNamespaceSecretResponses,
    DeleteNamespaceSecretErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces/{namespace}/secrets/{key}", ...options });

export const putNamespaceSecret = <ThrowOnError extends boolean = false>(
  options: Options<PutNamespaceSecretData, ThrowOnError>,
): RequestResult<
  PutNamespaceSecretResponses,
  PutNamespaceSecretErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutNamespaceSecretResponses,
    PutNamespaceSecretErrors,
    ThrowOnError
  >({
    url: "/api/v1/namespaces/{namespace}/secrets/{key}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const checkNamespaceSecret = <ThrowOnError extends boolean = false>(
  options: Options<CheckNamespaceSecretData, ThrowOnError>,
): RequestResult<
  CheckNamespaceSecretResponses,
  CheckNamespaceSecretErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CheckNamespaceSecretResponses,
    CheckNamespaceSecretErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces/{namespace}/secrets/{key}/check", ...options });

export const validateFile = <ThrowOnError extends boolean = false>(
  options: Options<ValidateFileData, ThrowOnError>,
): RequestResult<ValidateFileResponses, ValidateFileErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ValidateFileResponses,
    ValidateFileErrors,
    ThrowOnError
  >({
    url: "/api/v1/namespaces/{namespace}/validate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const listNamespaceVariables = <ThrowOnError extends boolean = false>(
  options: Options<ListNamespaceVariablesData, ThrowOnError>,
): RequestResult<
  ListNamespaceVariablesResponses,
  ListNamespaceVariablesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListNamespaceVariablesResponses,
    ListNamespaceVariablesErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces/{namespace}/variables", ...options });

export const deleteNamespaceVariable = <ThrowOnError extends boolean = false>(
  options: Options<DeleteNamespaceVariableData, ThrowOnError>,
): RequestResult<
  DeleteNamespaceVariableResponses,
  DeleteNamespaceVariableErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteNamespaceVariableResponses,
    DeleteNamespaceVariableErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces/{namespace}/variables/{key}", ...options });

export const putNamespaceVariable = <ThrowOnError extends boolean = false>(
  options: Options<PutNamespaceVariableData, ThrowOnError>,
): RequestResult<
  PutNamespaceVariableResponses,
  PutNamespaceVariableErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutNamespaceVariableResponses,
    PutNamespaceVariableErrors,
    ThrowOnError
  >({
    url: "/api/v1/namespaces/{namespace}/variables/{key}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const listVersions = <ThrowOnError extends boolean = false>(
  options: Options<ListVersionsData, ThrowOnError>,
): RequestResult<ListVersionsResponses, ListVersionsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListVersionsResponses,
    ListVersionsErrors,
    ThrowOnError
  >({ url: "/api/v1/namespaces/{namespace}/versions", ...options });

export const listUpcomingSchedules = <ThrowOnError extends boolean = false>(
  options?: Options<ListUpcomingSchedulesData, ThrowOnError>,
): RequestResult<
  ListUpcomingSchedulesResponses,
  ListUpcomingSchedulesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListUpcomingSchedulesResponses,
    ListUpcomingSchedulesErrors,
    ThrowOnError
  >({ url: "/api/v1/schedules/upcoming", ...options });

export const getFlowSchema = <ThrowOnError extends boolean = false>(
  options?: Options<GetFlowSchemaData, ThrowOnError>,
): RequestResult<GetFlowSchemaResponses, GetFlowSchemaErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetFlowSchemaResponses,
    GetFlowSchemaErrors,
    ThrowOnError
  >({ url: "/api/v1/schemas/flow.json", ...options });

export const listSecretProviders = <ThrowOnError extends boolean = false>(
  options?: Options<ListSecretProvidersData, ThrowOnError>,
): RequestResult<
  ListSecretProvidersResponses,
  ListSecretProvidersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListSecretProvidersResponses,
    ListSecretProvidersErrors,
    ThrowOnError
  >({ url: "/api/v1/secret-providers", ...options });

export const createSecretProvider = <ThrowOnError extends boolean = false>(
  options: Options<CreateSecretProviderData, ThrowOnError>,
): RequestResult<
  CreateSecretProviderResponses,
  CreateSecretProviderErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSecretProviderResponses,
    CreateSecretProviderErrors,
    ThrowOnError
  >({
    url: "/api/v1/secret-providers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deleteSecretProvider = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSecretProviderData, ThrowOnError>,
): RequestResult<
  DeleteSecretProviderResponses,
  DeleteSecretProviderErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteSecretProviderResponses,
    DeleteSecretProviderErrors,
    ThrowOnError
  >({ url: "/api/v1/secret-providers/{name}", ...options });

export const updateSecretProvider = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSecretProviderData, ThrowOnError>,
): RequestResult<
  UpdateSecretProviderResponses,
  UpdateSecretProviderErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateSecretProviderResponses,
    UpdateSecretProviderErrors,
    ThrowOnError
  >({
    url: "/api/v1/secret-providers/{name}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const checkSecretProvider = <ThrowOnError extends boolean = false>(
  options: Options<CheckSecretProviderData, ThrowOnError>,
): RequestResult<
  CheckSecretProviderResponses,
  CheckSecretProviderErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CheckSecretProviderResponses,
    CheckSecretProviderErrors,
    ThrowOnError
  >({
    url: "/api/v1/secret-providers/{name}/check",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const listGlobalSecrets = <ThrowOnError extends boolean = false>(
  options?: Options<ListGlobalSecretsData, ThrowOnError>,
): RequestResult<
  ListGlobalSecretsResponses,
  ListGlobalSecretsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListGlobalSecretsResponses,
    ListGlobalSecretsErrors,
    ThrowOnError
  >({ url: "/api/v1/secrets", ...options });

export const deleteGlobalSecret = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGlobalSecretData, ThrowOnError>,
): RequestResult<
  DeleteGlobalSecretResponses,
  DeleteGlobalSecretErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteGlobalSecretResponses,
    DeleteGlobalSecretErrors,
    ThrowOnError
  >({ url: "/api/v1/secrets/{key}", ...options });

export const putGlobalSecret = <ThrowOnError extends boolean = false>(
  options: Options<PutGlobalSecretData, ThrowOnError>,
): RequestResult<
  PutGlobalSecretResponses,
  PutGlobalSecretErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutGlobalSecretResponses,
    PutGlobalSecretErrors,
    ThrowOnError
  >({
    url: "/api/v1/secrets/{key}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const checkGlobalSecret = <ThrowOnError extends boolean = false>(
  options: Options<CheckGlobalSecretData, ThrowOnError>,
): RequestResult<
  CheckGlobalSecretResponses,
  CheckGlobalSecretErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CheckGlobalSecretResponses,
    CheckGlobalSecretErrors,
    ThrowOnError
  >({ url: "/api/v1/secrets/{key}/check", ...options });

export const listTokens = <ThrowOnError extends boolean = false>(
  options?: Options<ListTokensData, ThrowOnError>,
): RequestResult<ListTokensResponses, ListTokensErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListTokensResponses,
    ListTokensErrors,
    ThrowOnError
  >({ url: "/api/v1/tokens", ...options });

export const createToken = <ThrowOnError extends boolean = false>(
  options: Options<CreateTokenData, ThrowOnError>,
): RequestResult<CreateTokenResponses, CreateTokenErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateTokenResponses,
    CreateTokenErrors,
    ThrowOnError
  >({
    url: "/api/v1/tokens",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const revokeToken = <ThrowOnError extends boolean = false>(
  options: Options<RevokeTokenData, ThrowOnError>,
): RequestResult<RevokeTokenResponses, RevokeTokenErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    RevokeTokenResponses,
    RevokeTokenErrors,
    ThrowOnError
  >({ url: "/api/v1/tokens/{tokenId}", ...options });

export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>,
): RequestResult<ListUsersResponses, ListUsersErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListUsersResponses,
    ListUsersErrors,
    ThrowOnError
  >({ url: "/api/v1/users", ...options });

export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>,
): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    url: "/api/v1/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>,
): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    UpdateUserResponses,
    UpdateUserErrors,
    ThrowOnError
  >({
    url: "/api/v1/users/{userId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const resetUserPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserPasswordData, ThrowOnError>,
): RequestResult<
  ResetUserPasswordResponses,
  ResetUserPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ResetUserPasswordResponses,
    ResetUserPasswordErrors,
    ThrowOnError
  >({
    url: "/api/v1/users/{userId}/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const listGlobalVariables = <ThrowOnError extends boolean = false>(
  options?: Options<ListGlobalVariablesData, ThrowOnError>,
): RequestResult<
  ListGlobalVariablesResponses,
  ListGlobalVariablesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListGlobalVariablesResponses,
    ListGlobalVariablesErrors,
    ThrowOnError
  >({ url: "/api/v1/variables", ...options });

export const deleteGlobalVariable = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGlobalVariableData, ThrowOnError>,
): RequestResult<
  DeleteGlobalVariableResponses,
  DeleteGlobalVariableErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteGlobalVariableResponses,
    DeleteGlobalVariableErrors,
    ThrowOnError
  >({ url: "/api/v1/variables/{key}", ...options });

export const putGlobalVariable = <ThrowOnError extends boolean = false>(
  options: Options<PutGlobalVariableData, ThrowOnError>,
): RequestResult<
  PutGlobalVariableResponses,
  PutGlobalVariableErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutGlobalVariableResponses,
    PutGlobalVariableErrors,
    ThrowOnError
  >({
    url: "/api/v1/variables/{key}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Start the flow of a webhook trigger
 */
export const fireWebhook = <ThrowOnError extends boolean = false>(
  options: Options<FireWebhookData, ThrowOnError>,
): RequestResult<FireWebhookResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<FireWebhookResponses, unknown, ThrowOnError>({
    url: "/hooks/{key}",
    ...options,
  });
