// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Artifact = {
  content_type: string;
  created_at: string;
  id: string;
  name: string;
  size: number;
  task_key: string;
  task_run_id: string;
  [key: string]: unknown;
};

export type ArtifactList = {
  items: Array<Artifact>;
  [key: string]: unknown;
};

export type AuditEvent = {
  action: string;
  actor_id: string;
  actor_label: string;
  actor_type: "user" | "token" | "system" | "ai";
  details: {
    [key: string]: unknown;
  };
  id: string;
  ip: string;
  target_id: string;
  target_type: string;
  ts: string;
  [key: string]: unknown;
};

export type AuditList = {
  items: Array<AuditEvent>;
  next_cursor?: string;
  [key: string]: unknown;
};

export type ChangePasswordRequest = {
  current_password: string;
  new_password: string;
  [key: string]: unknown;
};

export type CountResult = {
  count: number;
  [key: string]: unknown;
};

export type CreateNamespaceRequest = {
  description?: string;
  name: string;
  [key: string]: unknown;
};

export type CreateTokenRequest = {
  expires_in_days?: number;
  name: string;
  role: "viewer" | "operator" | "editor" | "admin";
  [key: string]: unknown;
};

export type CreateUserRequest = {
  email: string;
  name?: string;
  /**
   * Temporary password. The user must change it at first login.
   */
  password: string;
  role: "viewer" | "operator" | "editor" | "admin";
  [key: string]: unknown;
};

export type CreatedToken = {
  secret: string;
  token: Token;
  [key: string]: unknown;
};

export type ErrorBody = {
  code: string;
  details?: unknown;
  message: string;
  [key: string]: unknown;
};

export type ErrorEnvelope = {
  error: ErrorBody;
  [key: string]: unknown;
};

export type ExecutionDetail = {
  chain_depth: number;
  children: Array<ExecutionRef>;
  created_at: string;
  created_by: string;
  duration_ms?: number | null;
  ended_at?: string | null;
  error: string;
  /**
   * Flow ID. Null for file runs.
   */
  flow_id?: string | null;
  flow_revision_id?: string | null;
  git_sha?: string;
  id: string;
  inputs: {
    [key: string]: unknown;
  };
  labels: {
    [key: string]: string;
  };
  namespace: string;
  outputs?: {
    [key: string]: unknown;
  } | null;
  parent_execution_id?: string | null;
  reason: string;
  restart_of_id?: string | null;
  secret_keys_used: Array<string>;
  snapshot_id: string;
  snapshot_version?: number | null;
  started_at?: string | null;
  state:
    | "QUEUED"
    | "RUNNING"
    | "CANCELLING"
    | "SUCCESS"
    | "FAILED"
    | "TIMED_OUT"
    | "CANCELLED"
    | "SKIPPED";
  task_runs: Array<TaskRun>;
  trigger_payload: {
    [key: string]: unknown;
  };
  trigger_type: string;
  [key: string]: unknown;
};

export type ExecutionList = {
  items: Array<ExecutionSummary>;
  next_cursor?: string;
  [key: string]: unknown;
};

export type ExecutionRef = {
  created_at: string;
  id: string;
  state: string;
  [key: string]: unknown;
};

export type ExecutionSummary = {
  created_at: string;
  created_by: string;
  duration_ms?: number | null;
  ended_at?: string | null;
  error: string;
  /**
   * Flow ID. Null for file runs.
   */
  flow_id?: string | null;
  id: string;
  labels: {
    [key: string]: string;
  };
  namespace: string;
  reason: string;
  started_at?: string | null;
  state:
    | "QUEUED"
    | "RUNNING"
    | "CANCELLING"
    | "SUCCESS"
    | "FAILED"
    | "TIMED_OUT"
    | "CANCELLED"
    | "SKIPPED";
  trigger_type: string;
  [key: string]: unknown;
};

export type FileChange = {
  /**
   * put only. UTF-8 text content.
   */
  content?: string;
  /**
   * put only. Binary content as base64. Used instead of content.
   */
  content_base64?: string;
  executable?: boolean;
  /**
   * rename only.
   */
  new_path?: string;
  op: "put" | "delete" | "rename";
  path: string;
  [key: string]: unknown;
};

export type FileDiff = {
  binary: boolean;
  /**
   * Unified diff for text files.
   */
  diff: string;
  path: string;
  status: "added" | "removed" | "modified";
  [key: string]: unknown;
};

export type FileEntry = {
  executable: boolean;
  hash: string;
  path: string;
  size: number;
  [key: string]: unknown;
};

export type FileList = {
  git_sha?: string;
  items: Array<FileEntry>;
  snapshot_id?: string | null;
  version?: number | null;
  [key: string]: unknown;
};

export type FlowDetail = {
  description: string;
  disabled: boolean;
  error_count: number;
  flow_id: string;
  id: string;
  labels?: {
    [key: string]: string;
  };
  last_execution?: ExecutionRef;
  namespace: string;
  path: string;
  revision?: Revision;
  triggers: Array<TriggerInfo>;
  valid: boolean;
  [key: string]: unknown;
};

export type FlowList = {
  items: Array<FlowSummary>;
  next_cursor?: string;
  [key: string]: unknown;
};

export type FlowSummary = {
  description: string;
  disabled: boolean;
  error_count: number;
  flow_id: string;
  id: string;
  labels?: {
    [key: string]: string;
  };
  last_execution?: ExecutionRef;
  namespace: string;
  path: string;
  valid: boolean;
  [key: string]: unknown;
};

export type Instance = {
  executors: Array<string>;
  heartbeat_at: string;
  hostname: string;
  id: string;
  online: boolean;
  pools: Array<string>;
  started_at: string;
  version: string;
  [key: string]: unknown;
};

export type InstanceList = {
  items: Array<Instance>;
  [key: string]: unknown;
};

export type Issue = {
  code: string;
  column: number;
  line: number;
  message: string;
  path: string;
  [key: string]: unknown;
};

export type LogEntry = {
  attempt: number;
  /**
   * 1-based line number in the task run.
   */
  n: number;
  stream: "stdout" | "stderr" | "system";
  task_key: string;
  task_run_id: string;
  text: string;
  ts: string;
  [key: string]: unknown;
};

export type LogPage = {
  /**
   * True when the execution ended and no more lines follow.
   */
  done: boolean;
  lines: Array<LogEntry>;
  next_cursor?: string;
  [key: string]: unknown;
};

export type LoginRequest = {
  email: string;
  password: string;
  [key: string]: unknown;
};

export type Me = {
  auth_type: "session" | "token";
  email: string;
  id: string;
  must_change_password: boolean;
  name: string;
  role: "viewer" | "operator" | "editor" | "admin";
  [key: string]: unknown;
};

export type MetricList = {
  items: Array<MetricPoint>;
  [key: string]: unknown;
};

export type MetricPoint = {
  name: string;
  tags: {
    [key: string]: string;
  };
  task_key: string;
  task_run_id: string;
  ts: string;
  unit: string;
  value: number;
  [key: string]: unknown;
};

export type Namespace = {
  description: string;
  git_source_id?: string | null;
  head_git_sha?: string;
  head_version?: number | null;
  /**
   * True for a parent that exists only because of its children.
   */
  implicit: boolean;
  name: string;
  parent?: string;
  read_only?: boolean;
  source_type: "managed" | "git" | "implicit";
  [key: string]: unknown;
};

export type NamespaceList = {
  items: Array<Namespace>;
  [key: string]: unknown;
};

export type ResetPasswordRequest = {
  password: string;
  [key: string]: unknown;
};

export type RevertRequest = {
  message?: string;
  version: number;
  [key: string]: unknown;
};

export type Revision = {
  created_at: string;
  definition?: {
    [key: string]: unknown;
  } | null;
  errors: Array<Issue>;
  git_sha?: string;
  id: string;
  message?: string;
  path: string;
  snapshot_version?: number | null;
  source: string;
  valid: boolean;
  [key: string]: unknown;
};

export type RevisionList = {
  items: Array<RevisionSummary>;
  [key: string]: unknown;
};

export type RevisionSummary = {
  created_at: string;
  error_count: number;
  git_sha?: string;
  id: string;
  message?: string;
  snapshot_version?: number | null;
  valid: boolean;
  [key: string]: unknown;
};

export type RunFileRequest = {
  args?: Array<string>;
  path: string;
  [key: string]: unknown;
};

export type RunnerComplete = {
  error: string;
  exit_code: number;
  reason?: string;
  [key: string]: unknown;
};

export type RunnerEvent = {
  key?: string;
  name?: string;
  tags?: {
    [key: string]: string;
  };
  ts?: string;
  type: "output" | "metric";
  unit?: string;
  value?: unknown;
  [key: string]: unknown;
};

export type RunnerEventBatch = {
  events: Array<RunnerEvent>;
  seq: number;
  [key: string]: unknown;
};

export type RunnerHeartbeatResponse = {
  cancel: boolean;
  [key: string]: unknown;
};

export type RunnerLimits = {
  max_artifact_bytes: number;
  max_bundle_bytes: number;
  [key: string]: unknown;
};

export type RunnerLogBatch = {
  lines: Array<RunnerLogLine>;
  seq: number;
  [key: string]: unknown;
};

export type RunnerLogLine = {
  stream: "stdout" | "stderr" | "system";
  text: string;
  ts: string;
  [key: string]: unknown;
};

export type RunnerSpec = {
  attempt: number;
  bundle_hash: string;
  command: Array<string>;
  env: {
    [key: string]: string;
  };
  execution_id: string;
  flow_id: string;
  limits: RunnerLimits;
  mask_values: Array<string>;
  namespace: string;
  runtime?: string;
  task_id: string;
  task_run_id: string;
  timeout_seconds: number;
  workdir: string;
  [key: string]: unknown;
};

export type SaveChangesRequest = {
  /**
   * Fails with 409 version_conflict when the head version differs.
   */
  base_version?: number;
  changes: Array<FileChange>;
  message: string;
  [key: string]: unknown;
};

export type Snapshot = {
  author: string;
  created_at: string;
  file_count: number;
  git_sha?: string;
  id: string;
  manifest_hash: string;
  message: string;
  version?: number | null;
  [key: string]: unknown;
};

export type SnapshotList = {
  items: Array<Snapshot>;
  [key: string]: unknown;
};

export type TaskRun = {
  attempt: number;
  child_execution_id?: string | null;
  duration_ms?: number | null;
  ended_at?: string | null;
  error: string;
  executor_type: string;
  exit_code?: number | null;
  id: string;
  outputs?: {
    [key: string]: unknown;
  } | null;
  pool: string;
  queued_at?: string | null;
  reason: string;
  reused_from_id?: string | null;
  started_at?: string | null;
  state:
    | "PENDING"
    | "QUEUED"
    | "RUNNING"
    | "SUCCESS"
    | "FAILED"
    | "TIMED_OUT"
    | "CANCELLED"
    | "SKIPPED";
  task_key: string;
  task_type: string;
  [key: string]: unknown;
};

export type TextDiff = {
  diff: string;
  [key: string]: unknown;
};

export type Token = {
  created_at: string;
  expires_at?: string;
  id: string;
  last_used_at?: string;
  name: string;
  prefix: string;
  revoked_at?: string;
  role: "viewer" | "operator" | "editor" | "admin";
  user_email: string;
  user_id: string;
  [key: string]: unknown;
};

export type TokenList = {
  items: Array<Token>;
  next_cursor?: string;
  [key: string]: unknown;
};

export type TriggerInfo = {
  active: boolean;
  config: {
    [key: string]: unknown;
  };
  has_webhook_key: boolean;
  key: string;
  last_fired_at?: string | null;
  next_fire_at?: string | null;
  type: "schedule" | "webhook" | "flow";
  [key: string]: unknown;
};

export type TriggerRequest = {
  inputs?: {
    [key: string]: unknown;
  };
  labels?: {
    [key: string]: string;
  };
  [key: string]: unknown;
};

export type UpdateFlowRequest = {
  disabled: boolean;
  [key: string]: unknown;
};

export type UpdateMeRequest = {
  name: string;
  [key: string]: unknown;
};

export type UpdateUserRequest = {
  disabled?: boolean;
  name?: string;
  role?: "viewer" | "operator" | "editor" | "admin";
  [key: string]: unknown;
};

export type User = {
  created_at: string;
  disabled: boolean;
  email: string;
  id: string;
  last_login_at?: string;
  must_change_password: boolean;
  name: string;
  role: "viewer" | "operator" | "editor" | "admin";
  [key: string]: unknown;
};

export type UserList = {
  items: Array<User>;
  next_cursor?: string;
  [key: string]: unknown;
};

export type ValidateFileRequest = {
  content: string;
  path: string;
  [key: string]: unknown;
};

export type ValidateFileResult = {
  errors: Array<Issue>;
  flow_id?: string;
  kind: "flow" | "namespace" | "other";
  valid: boolean;
  [key: string]: unknown;
};

export type VersionDiff = {
  files: Array<FileDiff>;
  from: number;
  to: number;
  [key: string]: unknown;
};

export type RunnerPutArtifactData = {
  body: Blob | File;
  path: {
    taskRunId: string;
    name: string;
  };
  query?: never;
  url: "/api/runner/v1/task-runs/{taskRunId}/artifacts/{name}";
};

export type RunnerPutArtifactResponses = {
  /**
   * Stored.
   */
  204: void;
};

export type RunnerPutArtifactResponse =
  RunnerPutArtifactResponses[keyof RunnerPutArtifactResponses];

export type RunnerGetBundleData = {
  body?: never;
  path: {
    taskRunId: string;
  };
  query?: never;
  url: "/api/runner/v1/task-runs/{taskRunId}/bundle";
};

export type RunnerGetBundleResponses = {
  /**
   * Bundle.
   */
  200: Blob | File;
};

export type RunnerGetBundleResponse =
  RunnerGetBundleResponses[keyof RunnerGetBundleResponses];

export type RunnerCompleteData = {
  body: RunnerComplete;
  path: {
    taskRunId: string;
  };
  query?: never;
  url: "/api/runner/v1/task-runs/{taskRunId}/complete";
};

export type RunnerCompleteErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RunnerCompleteError =
  RunnerCompleteErrors[keyof RunnerCompleteErrors];

export type RunnerCompleteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type RunnerCompleteResponse =
  RunnerCompleteResponses[keyof RunnerCompleteResponses];

export type RunnerPostEventsData = {
  body: RunnerEventBatch;
  path: {
    taskRunId: string;
  };
  query?: never;
  url: "/api/runner/v1/task-runs/{taskRunId}/events";
};

export type RunnerPostEventsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RunnerPostEventsError =
  RunnerPostEventsErrors[keyof RunnerPostEventsErrors];

export type RunnerPostEventsResponses = {
  /**
   * No Content
   */
  204: void;
};

export type RunnerPostEventsResponse =
  RunnerPostEventsResponses[keyof RunnerPostEventsResponses];

export type RunnerHeartbeatData = {
  body?: never;
  path: {
    taskRunId: string;
  };
  query?: never;
  url: "/api/runner/v1/task-runs/{taskRunId}/heartbeat";
};

export type RunnerHeartbeatErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RunnerHeartbeatError =
  RunnerHeartbeatErrors[keyof RunnerHeartbeatErrors];

export type RunnerHeartbeatResponses = {
  /**
   * OK
   */
  200: RunnerHeartbeatResponse;
};

export type RunnerHeartbeatResponse2 =
  RunnerHeartbeatResponses[keyof RunnerHeartbeatResponses];

export type RunnerPostLogsData = {
  body: RunnerLogBatch;
  path: {
    taskRunId: string;
  };
  query?: never;
  url: "/api/runner/v1/task-runs/{taskRunId}/logs";
};

export type RunnerPostLogsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RunnerPostLogsError =
  RunnerPostLogsErrors[keyof RunnerPostLogsErrors];

export type RunnerPostLogsResponses = {
  /**
   * No Content
   */
  204: void;
};

export type RunnerPostLogsResponse =
  RunnerPostLogsResponses[keyof RunnerPostLogsResponses];

export type RunnerGetSpecData = {
  body?: never;
  path: {
    taskRunId: string;
  };
  query?: never;
  url: "/api/runner/v1/task-runs/{taskRunId}/spec";
};

export type RunnerGetSpecErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RunnerGetSpecError = RunnerGetSpecErrors[keyof RunnerGetSpecErrors];

export type RunnerGetSpecResponses = {
  /**
   * OK
   */
  200: RunnerSpec;
};

export type RunnerGetSpecResponse =
  RunnerGetSpecResponses[keyof RunnerGetSpecResponses];

export type ListAuditEventsData = {
  body?: never;
  path?: never;
  query?: {
    actor?: string;
    action?: string;
    target?: string;
    from?: string;
    to?: string;
    cursor?: string;
    limit?: number;
  };
  url: "/api/v1/audit";
};

export type ListAuditEventsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListAuditEventsError =
  ListAuditEventsErrors[keyof ListAuditEventsErrors];

export type ListAuditEventsResponses = {
  /**
   * OK
   */
  200: AuditList;
};

export type ListAuditEventsResponse =
  ListAuditEventsResponses[keyof ListAuditEventsResponses];

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/login";
};

export type LoginErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * OK
   */
  200: Me;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/logout";
};

export type LogoutErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * No Content
   */
  204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type GetMeErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
  /**
   * OK
   */
  200: Me;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateMeData = {
  body: UpdateMeRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type UpdateMeErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
  /**
   * OK
   */
  200: Me;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type ChangePasswordData = {
  body: ChangePasswordRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/password";
};

export type ChangePasswordErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ChangePasswordError =
  ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
  /**
   * No Content
   */
  204: void;
};

export type ChangePasswordResponse =
  ChangePasswordResponses[keyof ChangePasswordResponses];

export type RevokeOtherSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/sessions/revoke-others";
};

export type RevokeOtherSessionsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RevokeOtherSessionsError =
  RevokeOtherSessionsErrors[keyof RevokeOtherSessionsErrors];

export type RevokeOtherSessionsResponses = {
  /**
   * OK
   */
  200: CountResult;
};

export type RevokeOtherSessionsResponse =
  RevokeOtherSessionsResponses[keyof RevokeOtherSessionsResponses];

export type ListExecutionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Comma-separated execution states.
     */
    state?: string;
    /**
     * Namespace and its children.
     */
    namespace?: string;
    /**
     * Flow as <namespace>/<flow_id>.
     */
    flow?: string;
    trigger_type?:
      | "manual"
      | "schedule"
      | "webhook"
      | "flow"
      | "file"
      | "subflow"
      | "rerun"
      | "restart";
    /**
     * Label filter key=value. Repeat for several labels.
     */
    label?: Array<string>;
    from?: string;
    to?: string;
    sort?: "created" | "duration";
    /**
     * Opaque cursor from next_cursor of the previous page.
     */
    cursor?: string;
    limit?: number;
  };
  url: "/api/v1/executions";
};

export type ListExecutionsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListExecutionsError =
  ListExecutionsErrors[keyof ListExecutionsErrors];

export type ListExecutionsResponses = {
  /**
   * OK
   */
  200: ExecutionList;
};

export type ListExecutionsResponse =
  ListExecutionsResponses[keyof ListExecutionsResponses];

export type GetExecutionData = {
  body?: never;
  path: {
    executionId: string;
  };
  query?: never;
  url: "/api/v1/executions/{executionId}";
};

export type GetExecutionErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type GetExecutionError = GetExecutionErrors[keyof GetExecutionErrors];

export type GetExecutionResponses = {
  /**
   * OK
   */
  200: ExecutionDetail;
};

export type GetExecutionResponse =
  GetExecutionResponses[keyof GetExecutionResponses];

export type ListExecutionArtifactsData = {
  body?: never;
  path: {
    executionId: string;
  };
  query?: never;
  url: "/api/v1/executions/{executionId}/artifacts";
};

export type ListExecutionArtifactsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListExecutionArtifactsError =
  ListExecutionArtifactsErrors[keyof ListExecutionArtifactsErrors];

export type ListExecutionArtifactsResponses = {
  /**
   * OK
   */
  200: ArtifactList;
};

export type ListExecutionArtifactsResponse =
  ListExecutionArtifactsResponses[keyof ListExecutionArtifactsResponses];

export type DownloadArtifactData = {
  body?: never;
  path: {
    executionId: string;
    artifactId: string;
  };
  query?: never;
  url: "/api/v1/executions/{executionId}/artifacts/{artifactId}";
};

export type DownloadArtifactResponses = {
  /**
   * Artifact content.
   */
  200: Blob | File;
};

export type DownloadArtifactResponse =
  DownloadArtifactResponses[keyof DownloadArtifactResponses];

export type CancelExecutionData = {
  body?: never;
  path: {
    executionId: string;
  };
  query?: never;
  url: "/api/v1/executions/{executionId}/cancel";
};

export type CancelExecutionErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type CancelExecutionError =
  CancelExecutionErrors[keyof CancelExecutionErrors];

export type CancelExecutionResponses = {
  /**
   * Accepted
   */
  202: ExecutionDetail;
};

export type CancelExecutionResponse =
  CancelExecutionResponses[keyof CancelExecutionResponses];

export type StreamExecutionEventsData = {
  body?: never;
  headers?: {
    "Last-Event-ID"?: string;
  };
  path: {
    executionId: string;
  };
  query?: never;
  url: "/api/v1/executions/{executionId}/events";
};

export type StreamExecutionEventsResponses = {
  /**
   * Event stream.
   */
  200: unknown;
};

export type GetExecutionLogsData = {
  body?: never;
  path: {
    executionId: string;
  };
  query?: {
    /**
     * Task ID filter.
     */
    task?: string;
    /**
     * Case-insensitive text filter.
     */
    search?: string;
    /**
     * Opaque cursor from next_cursor of the previous page.
     */
    cursor?: string;
    limit?: number;
  };
  url: "/api/v1/executions/{executionId}/logs";
};

export type GetExecutionLogsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type GetExecutionLogsError =
  GetExecutionLogsErrors[keyof GetExecutionLogsErrors];

export type GetExecutionLogsResponses = {
  /**
   * OK
   */
  200: LogPage;
};

export type GetExecutionLogsResponse =
  GetExecutionLogsResponses[keyof GetExecutionLogsResponses];

export type DownloadExecutionLogsData = {
  body?: never;
  path: {
    executionId: string;
  };
  query?: {
    task?: string;
  };
  url: "/api/v1/executions/{executionId}/logs/download";
};

export type DownloadExecutionLogsResponses = {
  /**
   * Log file.
   */
  200: unknown;
};

export type StreamExecutionLogsData = {
  body?: never;
  headers?: {
    "Last-Event-ID"?: string;
  };
  path: {
    executionId: string;
  };
  query?: {
    task?: string;
  };
  url: "/api/v1/executions/{executionId}/logs/stream";
};

export type StreamExecutionLogsResponses = {
  /**
   * Event stream.
   */
  200: unknown;
};

export type ListExecutionMetricsData = {
  body?: never;
  path: {
    executionId: string;
  };
  query?: never;
  url: "/api/v1/executions/{executionId}/metrics";
};

export type ListExecutionMetricsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListExecutionMetricsError =
  ListExecutionMetricsErrors[keyof ListExecutionMetricsErrors];

export type ListExecutionMetricsResponses = {
  /**
   * OK
   */
  200: MetricList;
};

export type ListExecutionMetricsResponse =
  ListExecutionMetricsResponses[keyof ListExecutionMetricsResponses];

export type RerunExecutionData = {
  body?: never;
  path: {
    executionId: string;
  };
  query?: never;
  url: "/api/v1/executions/{executionId}/rerun";
};

export type RerunExecutionErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RerunExecutionError =
  RerunExecutionErrors[keyof RerunExecutionErrors];

export type RerunExecutionResponses = {
  /**
   * Created
   */
  201: ExecutionDetail;
};

export type RerunExecutionResponse =
  RerunExecutionResponses[keyof RerunExecutionResponses];

export type RestartExecutionData = {
  body?: never;
  path: {
    executionId: string;
  };
  query?: never;
  url: "/api/v1/executions/{executionId}/restart";
};

export type RestartExecutionErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RestartExecutionError =
  RestartExecutionErrors[keyof RestartExecutionErrors];

export type RestartExecutionResponses = {
  /**
   * Created
   */
  201: ExecutionDetail;
};

export type RestartExecutionResponse =
  RestartExecutionResponses[keyof RestartExecutionResponses];

export type ListFlowsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Namespace and its children.
     */
    namespace?: string;
    /**
     * Opaque cursor from next_cursor of the previous page.
     */
    cursor?: string;
    limit?: number;
  };
  url: "/api/v1/flows";
};

export type ListFlowsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListFlowsError = ListFlowsErrors[keyof ListFlowsErrors];

export type ListFlowsResponses = {
  /**
   * OK
   */
  200: FlowList;
};

export type ListFlowsResponse = ListFlowsResponses[keyof ListFlowsResponses];

export type GetFlowData = {
  body?: never;
  path: {
    namespace: string;
    flowId: string;
  };
  query?: never;
  url: "/api/v1/flows/{namespace}/{flowId}";
};

export type GetFlowErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type GetFlowError = GetFlowErrors[keyof GetFlowErrors];

export type GetFlowResponses = {
  /**
   * OK
   */
  200: FlowDetail;
};

export type GetFlowResponse = GetFlowResponses[keyof GetFlowResponses];

export type UpdateFlowData = {
  body: UpdateFlowRequest;
  path: {
    namespace: string;
    flowId: string;
  };
  query?: never;
  url: "/api/v1/flows/{namespace}/{flowId}";
};

export type UpdateFlowErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type UpdateFlowError = UpdateFlowErrors[keyof UpdateFlowErrors];

export type UpdateFlowResponses = {
  /**
   * OK
   */
  200: FlowDetail;
};

export type UpdateFlowResponse = UpdateFlowResponses[keyof UpdateFlowResponses];

export type DiffFlowRevisionsData = {
  body?: never;
  path: {
    namespace: string;
    flowId: string;
  };
  query: {
    from: string;
    to: string;
  };
  url: "/api/v1/flows/{namespace}/{flowId}/diff";
};

export type DiffFlowRevisionsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type DiffFlowRevisionsError =
  DiffFlowRevisionsErrors[keyof DiffFlowRevisionsErrors];

export type DiffFlowRevisionsResponses = {
  /**
   * OK
   */
  200: TextDiff;
};

export type DiffFlowRevisionsResponse =
  DiffFlowRevisionsResponses[keyof DiffFlowRevisionsResponses];

export type TriggerFlowData = {
  body: TriggerRequest;
  path: {
    namespace: string;
    flowId: string;
  };
  query?: never;
  url: "/api/v1/flows/{namespace}/{flowId}/executions";
};

export type TriggerFlowErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type TriggerFlowError = TriggerFlowErrors[keyof TriggerFlowErrors];

export type TriggerFlowResponses = {
  /**
   * Created
   */
  201: ExecutionDetail;
};

export type TriggerFlowResponse =
  TriggerFlowResponses[keyof TriggerFlowResponses];

export type ListFlowRevisionsData = {
  body?: never;
  path: {
    namespace: string;
    flowId: string;
  };
  query?: {
    limit?: number;
  };
  url: "/api/v1/flows/{namespace}/{flowId}/revisions";
};

export type ListFlowRevisionsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListFlowRevisionsError =
  ListFlowRevisionsErrors[keyof ListFlowRevisionsErrors];

export type ListFlowRevisionsResponses = {
  /**
   * OK
   */
  200: RevisionList;
};

export type ListFlowRevisionsResponse =
  ListFlowRevisionsResponses[keyof ListFlowRevisionsResponses];

export type GetFlowRevisionData = {
  body?: never;
  path: {
    namespace: string;
    flowId: string;
    revisionId: string;
  };
  query?: never;
  url: "/api/v1/flows/{namespace}/{flowId}/revisions/{revisionId}";
};

export type GetFlowRevisionErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type GetFlowRevisionError =
  GetFlowRevisionErrors[keyof GetFlowRevisionErrors];

export type GetFlowRevisionResponses = {
  /**
   * OK
   */
  200: Revision;
};

export type GetFlowRevisionResponse =
  GetFlowRevisionResponses[keyof GetFlowRevisionResponses];

export type ListInstancesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/instances";
};

export type ListInstancesErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListInstancesError = ListInstancesErrors[keyof ListInstancesErrors];

export type ListInstancesResponses = {
  /**
   * OK
   */
  200: InstanceList;
};

export type ListInstancesResponse =
  ListInstancesResponses[keyof ListInstancesResponses];

export type ListNamespacesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/namespaces";
};

export type ListNamespacesErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListNamespacesError =
  ListNamespacesErrors[keyof ListNamespacesErrors];

export type ListNamespacesResponses = {
  /**
   * OK
   */
  200: NamespaceList;
};

export type ListNamespacesResponse =
  ListNamespacesResponses[keyof ListNamespacesResponses];

export type CreateNamespaceData = {
  body: CreateNamespaceRequest;
  path?: never;
  query?: never;
  url: "/api/v1/namespaces";
};

export type CreateNamespaceErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type CreateNamespaceError =
  CreateNamespaceErrors[keyof CreateNamespaceErrors];

export type CreateNamespaceResponses = {
  /**
   * Created
   */
  201: Namespace;
};

export type CreateNamespaceResponse =
  CreateNamespaceResponses[keyof CreateNamespaceResponses];

export type DeleteNamespaceData = {
  body?: never;
  path: {
    namespace: string;
  };
  query?: never;
  url: "/api/v1/namespaces/{namespace}";
};

export type DeleteNamespaceErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type DeleteNamespaceError =
  DeleteNamespaceErrors[keyof DeleteNamespaceErrors];

export type DeleteNamespaceResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteNamespaceResponse =
  DeleteNamespaceResponses[keyof DeleteNamespaceResponses];

export type GetNamespaceData = {
  body?: never;
  path: {
    namespace: string;
  };
  query?: never;
  url: "/api/v1/namespaces/{namespace}";
};

export type GetNamespaceErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type GetNamespaceError = GetNamespaceErrors[keyof GetNamespaceErrors];

export type GetNamespaceResponses = {
  /**
   * OK
   */
  200: Namespace;
};

export type GetNamespaceResponse =
  GetNamespaceResponses[keyof GetNamespaceResponses];

export type SaveChangesData = {
  body: SaveChangesRequest;
  path: {
    namespace: string;
  };
  query?: never;
  url: "/api/v1/namespaces/{namespace}/changes";
};

export type SaveChangesErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type SaveChangesError = SaveChangesErrors[keyof SaveChangesErrors];

export type SaveChangesResponses = {
  /**
   * Created
   */
  201: Snapshot;
};

export type SaveChangesResponse =
  SaveChangesResponses[keyof SaveChangesResponses];

export type DiffVersionsData = {
  body?: never;
  path: {
    namespace: string;
  };
  query: {
    from: number;
    to: number;
  };
  url: "/api/v1/namespaces/{namespace}/diff";
};

export type DiffVersionsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type DiffVersionsError = DiffVersionsErrors[keyof DiffVersionsErrors];

export type DiffVersionsResponses = {
  /**
   * OK
   */
  200: VersionDiff;
};

export type DiffVersionsResponse =
  DiffVersionsResponses[keyof DiffVersionsResponses];

export type GetFileData = {
  body?: never;
  path: {
    namespace: string;
  };
  query: {
    /**
     * File path relative to the namespace root.
     */
    path: string;
    /**
     * Version number. Default is the head version.
     */
    version?: number;
  };
  url: "/api/v1/namespaces/{namespace}/file";
};

export type GetFileResponses = {
  /**
   * File content.
   */
  200: Blob | File;
};

export type GetFileResponse = GetFileResponses[keyof GetFileResponses];

export type UploadFileData = {
  body: Blob | File;
  path: {
    namespace: string;
  };
  query: {
    /**
     * File path relative to the namespace root.
     */
    path: string;
    message?: string;
    executable?: boolean;
  };
  url: "/api/v1/namespaces/{namespace}/file";
};

export type UploadFileResponses = {
  /**
   * New version.
   */
  201: unknown;
};

export type ListFilesData = {
  body?: never;
  path: {
    namespace: string;
  };
  query?: {
    /**
     * Version number. Default is the head version.
     */
    version?: number;
  };
  url: "/api/v1/namespaces/{namespace}/files";
};

export type ListFilesErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors];

export type ListFilesResponses = {
  /**
   * OK
   */
  200: FileList;
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type RevertVersionData = {
  body: RevertRequest;
  path: {
    namespace: string;
  };
  query?: never;
  url: "/api/v1/namespaces/{namespace}/revert";
};

export type RevertVersionErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RevertVersionError = RevertVersionErrors[keyof RevertVersionErrors];

export type RevertVersionResponses = {
  /**
   * Created
   */
  201: Snapshot;
};

export type RevertVersionResponse =
  RevertVersionResponses[keyof RevertVersionResponses];

export type RunFileData = {
  body: RunFileRequest;
  path: {
    namespace: string;
  };
  query?: never;
  url: "/api/v1/namespaces/{namespace}/run";
};

export type RunFileErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RunFileError = RunFileErrors[keyof RunFileErrors];

export type RunFileResponses = {
  /**
   * Created
   */
  201: ExecutionDetail;
};

export type RunFileResponse = RunFileResponses[keyof RunFileResponses];

export type ValidateFileData = {
  body: ValidateFileRequest;
  path: {
    namespace: string;
  };
  query?: never;
  url: "/api/v1/namespaces/{namespace}/validate";
};

export type ValidateFileErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ValidateFileError = ValidateFileErrors[keyof ValidateFileErrors];

export type ValidateFileResponses = {
  /**
   * OK
   */
  200: ValidateFileResult;
};

export type ValidateFileResponse =
  ValidateFileResponses[keyof ValidateFileResponses];

export type ListVersionsData = {
  body?: never;
  path: {
    namespace: string;
  };
  query?: {
    limit?: number;
  };
  url: "/api/v1/namespaces/{namespace}/versions";
};

export type ListVersionsErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListVersionsError = ListVersionsErrors[keyof ListVersionsErrors];

export type ListVersionsResponses = {
  /**
   * OK
   */
  200: SnapshotList;
};

export type ListVersionsResponse =
  ListVersionsResponses[keyof ListVersionsResponses];

export type GetFlowSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/schemas/flow.json";
};

export type GetFlowSchemaErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type GetFlowSchemaError = GetFlowSchemaErrors[keyof GetFlowSchemaErrors];

export type GetFlowSchemaResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ListTokensData = {
  body?: never;
  path?: never;
  query?: {
    cursor?: string;
    limit?: number;
    /**
     * All users. Needs admin.
     */
    all?: boolean;
  };
  url: "/api/v1/tokens";
};

export type ListTokensErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListTokensError = ListTokensErrors[keyof ListTokensErrors];

export type ListTokensResponses = {
  /**
   * OK
   */
  200: TokenList;
};

export type ListTokensResponse = ListTokensResponses[keyof ListTokensResponses];

export type CreateTokenData = {
  body: CreateTokenRequest;
  path?: never;
  query?: never;
  url: "/api/v1/tokens";
};

export type CreateTokenErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type CreateTokenError = CreateTokenErrors[keyof CreateTokenErrors];

export type CreateTokenResponses = {
  /**
   * Created
   */
  201: CreatedToken;
};

export type CreateTokenResponse =
  CreateTokenResponses[keyof CreateTokenResponses];

export type RevokeTokenData = {
  body?: never;
  path: {
    tokenId: string;
  };
  query?: never;
  url: "/api/v1/tokens/{tokenId}";
};

export type RevokeTokenErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type RevokeTokenError = RevokeTokenErrors[keyof RevokeTokenErrors];

export type RevokeTokenResponses = {
  /**
   * No Content
   */
  204: void;
};

export type RevokeTokenResponse =
  RevokeTokenResponses[keyof RevokeTokenResponses];

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: {
    cursor?: string;
    limit?: number;
  };
  url: "/api/v1/users";
};

export type ListUsersErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
  /**
   * OK
   */
  200: UserList;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body: CreateUserRequest;
  path?: never;
  query?: never;
  url: "/api/v1/users";
};

export type CreateUserErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  /**
   * Created
   */
  201: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type UpdateUserData = {
  body: UpdateUserRequest;
  path: {
    userId: string;
  };
  query?: never;
  url: "/api/v1/users/{userId}";
};

export type UpdateUserErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
  /**
   * OK
   */
  200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ResetUserPasswordData = {
  body: ResetPasswordRequest;
  path: {
    userId: string;
  };
  query?: never;
  url: "/api/v1/users/{userId}/reset-password";
};

export type ResetUserPasswordErrors = {
  /**
   * Error
   */
  default: ErrorEnvelope;
};

export type ResetUserPasswordError =
  ResetUserPasswordErrors[keyof ResetUserPasswordErrors];

export type ResetUserPasswordResponses = {
  /**
   * No Content
   */
  204: void;
};

export type ResetUserPasswordResponse =
  ResetUserPasswordResponses[keyof ResetUserPasswordResponses];
