package main

import (
	"os"
	"strings"
	"testing"
)

func TestForbidScan(t *testing.T) {
	rules, err := loadForbidRules("../../" + forbidWordsPath)
	if err != nil {
		t.Fatal(err)
	}
	marker := "TO" + "DO"
	skip := "t." + "Skip"
	files := map[string]string{
		"a.go":          "package a\n// " + marker + " fix\n",
		"b.go":          "package b\n// Code generated by x. DO NOT EDIT.\n// " + marker + "\n",
		"docs/x.go":     "// " + marker + "\n",
		"c_test.go":     "func TestX(t *testing.T) { " + skip + "(\"x\") }\n",
		"d.ts":          "const autodoToString = 1\n",
		"e.md":          marker + "\n",
		"tests/ui/a.ts": "test.o" + "nly('x')\n",
		"f.yaml":        "a: not " + "implemented\n",
		"g.go":          "var StatusNotImplemented = 1 // x\n",
	}
	read := func(p string) ([]byte, error) {
		s, ok := files[p]
		if !ok {
			return nil, os.ErrNotExist
		}
		return []byte(s), nil
	}
	var list []string
	for k := range files {
		list = append(list, k)
	}
	found, err := scanForbid(list, rules, read)
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]bool{}
	for _, f := range found {
		got[f.Path] = true
	}
	for _, want := range []string{"a.go", "c_test.go", "tests/ui/a.ts", "f.yaml"} {
		if !got[want] {
			t.Errorf("expected finding in %s", want)
		}
	}
	for _, not := range []string{"b.go", "docs/x.go", "d.ts", "e.md", "g.go"} {
		if got[not] {
			t.Errorf("unexpected finding in %s", not)
		}
	}
}

const sddFixture = `
| REQ-CORE-001 | x |
| REQ-CORE-002 | y |
| SI-01 | z |

- **SCN-CORE-001** [E] (REQ-CORE-001, SI-01) text.
- **SCN-CORE-002** [I] (REQ-CORE-002) text.
`

func fixtureSDD(t *testing.T) *SDD {
	t.Helper()
	dir := t.TempDir()
	wd, _ := os.Getwd()
	t.Cleanup(func() { _ = os.Chdir(wd) })
	_ = os.MkdirAll(dir+"/docs", 0o755)
	_ = os.WriteFile(dir+"/"+sddPath, []byte(sddFixture), 0o644)
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	s, err := loadSDD()
	if err != nil {
		t.Fatal(err)
	}
	return s
}

func TestTraceRules(t *testing.T) {
	s := fixtureSDD(t)
	res := computeTrace(s, []TestCase{
		{Name: "TestSCN_CORE_001_A", Status: "passed"},
		{Name: "SCN-CORE-002 ui", Status: "skipped"},
		{Name: "TestSCN_CORE_009_Unknown", Status: "passed"},
	})
	joined := strings.Join(res.Errors, "\n")
	if res.OK || !strings.Contains(joined, "rule 3: SCN-CORE-002") || !strings.Contains(joined, "rule 4") {
		t.Fatalf("errors: %s", joined)
	}
	res = computeTrace(s, []TestCase{
		{Name: "TestSCN_CORE_001_A", Status: "passed"},
		{Name: "SCN-CORE-002 ui", Status: "passed"},
		{Classname: "github.com/x/tests/review/round-1", Name: "TestF_1_1", Status: "passed"},
	})
	if !res.OK {
		t.Fatalf("errors: %v", res.Errors)
	}
}
