/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as VariablesRouteImport } from './routes/variables'
import { Route as ExecutionsIndexRouteImport } from './routes/executions/index'
import { Route as ExecutionsExecutionIdRouteImport } from './routes/executions/$executionId'
import { Route as FlowsIndexRouteImport } from './routes/flows/index'
import { Route as NamespacesIndexRouteImport } from './routes/namespaces/index'
import { Route as NamespacesNamespaceRouteImport } from './routes/namespaces/$namespace'
import { Route as SettingsAuditRouteImport } from './routes/settings/audit'
import { Route as SettingsGitRouteImport } from './routes/settings/git'
import { Route as SettingsInstancesRouteImport } from './routes/settings/instances'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsSecretProvidersRouteImport } from './routes/settings/secret-providers'
import { Route as SettingsTokensRouteImport } from './routes/settings/tokens'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as FlowsNamespaceFlowIdRouteImport } from './routes/flows/$namespace/$flowId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const VariablesRoute = VariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsIndexRoute = ExecutionsIndexRouteImport.update({
  id: '/executions/',
  path: '/executions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsExecutionIdRoute = ExecutionsExecutionIdRouteImport.update({
  id: '/executions/$executionId',
  path: '/executions/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsIndexRoute = FlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesIndexRoute = NamespacesIndexRouteImport.update({
  id: '/namespaces/',
  path: '/namespaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesNamespaceRoute = NamespacesNamespaceRouteImport.update({
  id: '/namespaces/$namespace',
  path: '/namespaces/$namespace',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGitRoute = SettingsGitRouteImport.update({
  id: '/settings/git',
  path: '/settings/git',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInstancesRoute = SettingsInstancesRouteImport.update({
  id: '/settings/instances',
  path: '/settings/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecretProvidersRoute = SettingsSecretProvidersRouteImport.update({
  id: '/settings/secret-providers',
  path: '/settings/secret-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTokensRoute = SettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsNamespaceFlowIdRoute = FlowsNamespaceFlowIdRouteImport.update({
  id: '/flows/$namespace/$flowId',
  path: '/flows/$namespace/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/secrets': typeof SecretsRoute
  '/variables': typeof VariablesRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
  '/namespaces/$namespace': typeof NamespacesNamespaceRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/instances': typeof SettingsInstancesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/secret-providers': typeof SettingsSecretProvidersRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/users': typeof SettingsUsersRoute
  '/executions/': typeof ExecutionsIndexRoute
  '/flows/': typeof FlowsIndexRoute
  '/namespaces/': typeof NamespacesIndexRoute
  '/flows/$namespace/$flowId': typeof FlowsNamespaceFlowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/secrets': typeof SecretsRoute
  '/variables': typeof VariablesRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
  '/namespaces/$namespace': typeof NamespacesNamespaceRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/instances': typeof SettingsInstancesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/secret-providers': typeof SettingsSecretProvidersRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/users': typeof SettingsUsersRoute
  '/executions': typeof ExecutionsIndexRoute
  '/flows': typeof FlowsIndexRoute
  '/namespaces': typeof NamespacesIndexRoute
  '/flows/$namespace/$flowId': typeof FlowsNamespaceFlowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/secrets': typeof SecretsRoute
  '/variables': typeof VariablesRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
  '/namespaces/$namespace': typeof NamespacesNamespaceRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/instances': typeof SettingsInstancesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/secret-providers': typeof SettingsSecretProvidersRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/users': typeof SettingsUsersRoute
  '/executions/': typeof ExecutionsIndexRoute
  '/flows/': typeof FlowsIndexRoute
  '/namespaces/': typeof NamespacesIndexRoute
  '/flows/$namespace/$flowId': typeof FlowsNamespaceFlowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/secrets'
    | '/variables'
    | '/executions/$executionId'
    | '/namespaces/$namespace'
    | '/settings/audit'
    | '/settings/git'
    | '/settings/instances'
    | '/settings/profile'
    | '/settings/secret-providers'
    | '/settings/tokens'
    | '/settings/users'
    | '/executions/'
    | '/flows/'
    | '/namespaces/'
    | '/flows/$namespace/$flowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/secrets'
    | '/variables'
    | '/executions/$executionId'
    | '/namespaces/$namespace'
    | '/settings/audit'
    | '/settings/git'
    | '/settings/instances'
    | '/settings/profile'
    | '/settings/secret-providers'
    | '/settings/tokens'
    | '/settings/users'
    | '/executions'
    | '/flows'
    | '/namespaces'
    | '/flows/$namespace/$flowId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/secrets'
    | '/variables'
    | '/executions/$executionId'
    | '/namespaces/$namespace'
    | '/settings/audit'
    | '/settings/git'
    | '/settings/instances'
    | '/settings/profile'
    | '/settings/secret-providers'
    | '/settings/tokens'
    | '/settings/users'
    | '/executions/'
    | '/flows/'
    | '/namespaces/'
    | '/flows/$namespace/$flowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SecretsRoute: typeof SecretsRoute
  VariablesRoute: typeof VariablesRoute
  ExecutionsExecutionIdRoute: typeof ExecutionsExecutionIdRoute
  NamespacesNamespaceRoute: typeof NamespacesNamespaceRoute
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsGitRoute: typeof SettingsGitRoute
  SettingsInstancesRoute: typeof SettingsInstancesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecretProvidersRoute: typeof SettingsSecretProvidersRoute
  SettingsTokensRoute: typeof SettingsTokensRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  ExecutionsIndexRoute: typeof ExecutionsIndexRoute
  FlowsIndexRoute: typeof FlowsIndexRoute
  NamespacesIndexRoute: typeof NamespacesIndexRoute
  FlowsNamespaceFlowIdRoute: typeof FlowsNamespaceFlowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variables': {
      id: '/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof VariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/': {
      id: '/executions/'
      path: '/executions'
      fullPath: '/executions/'
      preLoaderRoute: typeof ExecutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/$executionId': {
      id: '/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/executions/$executionId'
      preLoaderRoute: typeof ExecutionsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/': {
      id: '/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof FlowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces/': {
      id: '/namespaces/'
      path: '/namespaces'
      fullPath: '/namespaces/'
      preLoaderRoute: typeof NamespacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces/$namespace': {
      id: '/namespaces/$namespace'
      path: '/namespaces/$namespace'
      fullPath: '/namespaces/$namespace'
      preLoaderRoute: typeof NamespacesNamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audit': {
      id: '/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/git': {
      id: '/settings/git'
      path: '/settings/git'
      fullPath: '/settings/git'
      preLoaderRoute: typeof SettingsGitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/instances': {
      id: '/settings/instances'
      path: '/settings/instances'
      fullPath: '/settings/instances'
      preLoaderRoute: typeof SettingsInstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/secret-providers': {
      id: '/settings/secret-providers'
      path: '/settings/secret-providers'
      fullPath: '/settings/secret-providers'
      preLoaderRoute: typeof SettingsSecretProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$namespace/$flowId': {
      id: '/flows/$namespace/$flowId'
      path: '/flows/$namespace/$flowId'
      fullPath: '/flows/$namespace/$flowId'
      preLoaderRoute: typeof FlowsNamespaceFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SecretsRoute: SecretsRoute,
  VariablesRoute: VariablesRoute,
  ExecutionsExecutionIdRoute: ExecutionsExecutionIdRoute,
  NamespacesNamespaceRoute: NamespacesNamespaceRoute,
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsGitRoute: SettingsGitRoute,
  SettingsInstancesRoute: SettingsInstancesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecretProvidersRoute: SettingsSecretProvidersRoute,
  SettingsTokensRoute: SettingsTokensRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  ExecutionsIndexRoute: ExecutionsIndexRoute,
  FlowsIndexRoute: FlowsIndexRoute,
  NamespacesIndexRoute: NamespacesIndexRoute,
  FlowsNamespaceFlowIdRoute: FlowsNamespaceFlowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
