// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  cancelExecution,
  changePassword,
  checkGlobalSecret,
  checkNamespaceSecret,
  checkSecretProvider,
  createAiConversation,
  createGitSource,
  createNamespace,
  createSecretProvider,
  createToken,
  createUser,
  deleteAiConversation,
  deleteAiProvider,
  deleteGitSource,
  deleteGlobalSecret,
  deleteGlobalVariable,
  deleteNamespace,
  deleteNamespaceSecret,
  deleteNamespaceVariable,
  deleteSecretProvider,
  diffFlowRevisions,
  diffVersions,
  downloadArtifact,
  downloadExecutionLogs,
  fireWebhook,
  getAiConversation,
  getAiProvider,
  getAiStatus,
  getDashboard,
  getExecution,
  getExecutionLogs,
  getFile,
  getFlow,
  getFlowMetrics,
  getFlowRevision,
  getFlowSchema,
  getFlowStats,
  getGitSource,
  getMe,
  getNamespace,
  getNamespaceGit,
  getStorageStatus,
  gitWebhook,
  listAiConversations,
  listAuditEvents,
  listExecutionArtifacts,
  listExecutionInsights,
  listExecutionMetrics,
  listExecutions,
  listFiles,
  listFlowRevisions,
  listFlows,
  listGitSources,
  listGitSyncRuns,
  listGlobalSecrets,
  listGlobalVariables,
  listInstances,
  listNamespaces,
  listNamespaceSecrets,
  listNamespaceVariables,
  listSecretProviders,
  listTokens,
  listUpcomingSchedules,
  listUsers,
  listVersions,
  login,
  logout,
  type Options,
  pushNamespaceBranch,
  putAiProvider,
  putGlobalSecret,
  putGlobalVariable,
  putNamespaceSecret,
  putNamespaceVariable,
  requestTriage,
  rerunExecution,
  resetUserPassword,
  restartExecution,
  revertVersion,
  revokeOtherSessions,
  revokeToken,
  rotateWebhookKey,
  runFile,
  runnerComplete,
  runnerGetBundle,
  runnerGetSpec,
  runnerHeartbeat,
  runnerPostEvents,
  runnerPostLogs,
  runnerPutArtifact,
  saveChanges,
  syncGitSource,
  testAiProvider,
  triggerFlow,
  updateFlow,
  updateGitSource,
  updateMe,
  updateSecretProvider,
  updateUser,
  uploadFile,
  validateFile,
} from "../sdk.gen";
import type {
  CancelExecutionData,
  CancelExecutionError,
  CancelExecutionResponse,
  ChangePasswordData,
  ChangePasswordError,
  ChangePasswordResponse,
  CheckGlobalSecretData,
  CheckGlobalSecretError,
  CheckGlobalSecretResponse,
  CheckNamespaceSecretData,
  CheckNamespaceSecretError,
  CheckNamespaceSecretResponse,
  CheckSecretProviderData,
  CheckSecretProviderError,
  CheckSecretProviderResponse,
  CreateAiConversationData,
  CreateAiConversationError,
  CreateAiConversationResponse,
  CreateGitSourceData,
  CreateGitSourceError,
  CreateGitSourceResponse,
  CreateNamespaceData,
  CreateNamespaceError,
  CreateNamespaceResponse,
  CreateSecretProviderData,
  CreateSecretProviderError,
  CreateSecretProviderResponse,
  CreateTokenData,
  CreateTokenError,
  CreateTokenResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  DeleteAiConversationData,
  DeleteAiConversationError,
  DeleteAiConversationResponse,
  DeleteAiProviderData,
  DeleteAiProviderError,
  DeleteAiProviderResponse,
  DeleteGitSourceData,
  DeleteGitSourceError,
  DeleteGitSourceResponse,
  DeleteGlobalSecretData,
  DeleteGlobalSecretError,
  DeleteGlobalSecretResponse,
  DeleteGlobalVariableData,
  DeleteGlobalVariableError,
  DeleteGlobalVariableResponse,
  DeleteNamespaceData,
  DeleteNamespaceError,
  DeleteNamespaceResponse,
  DeleteNamespaceSecretData,
  DeleteNamespaceSecretError,
  DeleteNamespaceSecretResponse,
  DeleteNamespaceVariableData,
  DeleteNamespaceVariableError,
  DeleteNamespaceVariableResponse,
  DeleteSecretProviderData,
  DeleteSecretProviderError,
  DeleteSecretProviderResponse,
  DiffFlowRevisionsData,
  DiffFlowRevisionsError,
  DiffFlowRevisionsResponse,
  DiffVersionsData,
  DiffVersionsError,
  DiffVersionsResponse,
  DownloadArtifactData,
  DownloadArtifactResponse,
  DownloadExecutionLogsData,
  FireWebhookData,
  GetAiConversationData,
  GetAiConversationError,
  GetAiConversationResponse,
  GetAiProviderData,
  GetAiProviderError,
  GetAiProviderResponse,
  GetAiStatusData,
  GetAiStatusError,
  GetAiStatusResponse,
  GetDashboardData,
  GetDashboardError,
  GetDashboardResponse,
  GetExecutionData,
  GetExecutionError,
  GetExecutionLogsData,
  GetExecutionLogsError,
  GetExecutionLogsResponse,
  GetExecutionResponse,
  GetFileData,
  GetFileResponse,
  GetFlowData,
  GetFlowError,
  GetFlowMetricsData,
  GetFlowMetricsError,
  GetFlowMetricsResponse,
  GetFlowResponse,
  GetFlowRevisionData,
  GetFlowRevisionError,
  GetFlowRevisionResponse,
  GetFlowSchemaData,
  GetFlowSchemaError,
  GetFlowStatsData,
  GetFlowStatsError,
  GetFlowStatsResponse,
  GetGitSourceData,
  GetGitSourceError,
  GetGitSourceResponse,
  GetMeData,
  GetMeError,
  GetMeResponse,
  GetNamespaceData,
  GetNamespaceError,
  GetNamespaceGitData,
  GetNamespaceGitError,
  GetNamespaceGitResponse,
  GetNamespaceResponse,
  GetStorageStatusData,
  GetStorageStatusError,
  GetStorageStatusResponse,
  GitWebhookData,
  ListAiConversationsData,
  ListAiConversationsError,
  ListAiConversationsResponse,
  ListAuditEventsData,
  ListAuditEventsError,
  ListAuditEventsResponse,
  ListExecutionArtifactsData,
  ListExecutionArtifactsError,
  ListExecutionArtifactsResponse,
  ListExecutionInsightsData,
  ListExecutionInsightsError,
  ListExecutionInsightsResponse,
  ListExecutionMetricsData,
  ListExecutionMetricsError,
  ListExecutionMetricsResponse,
  ListExecutionsData,
  ListExecutionsError,
  ListExecutionsResponse,
  ListFilesData,
  ListFilesError,
  ListFilesResponse,
  ListFlowRevisionsData,
  ListFlowRevisionsError,
  ListFlowRevisionsResponse,
  ListFlowsData,
  ListFlowsError,
  ListFlowsResponse,
  ListGitSourcesData,
  ListGitSourcesError,
  ListGitSourcesResponse,
  ListGitSyncRunsData,
  ListGitSyncRunsError,
  ListGitSyncRunsResponse,
  ListGlobalSecretsData,
  ListGlobalSecretsError,
  ListGlobalSecretsResponse,
  ListGlobalVariablesData,
  ListGlobalVariablesError,
  ListGlobalVariablesResponse,
  ListInstancesData,
  ListInstancesError,
  ListInstancesResponse,
  ListNamespacesData,
  ListNamespaceSecretsData,
  ListNamespaceSecretsError,
  ListNamespaceSecretsResponse,
  ListNamespacesError,
  ListNamespacesResponse,
  ListNamespaceVariablesData,
  ListNamespaceVariablesError,
  ListNamespaceVariablesResponse,
  ListSecretProvidersData,
  ListSecretProvidersError,
  ListSecretProvidersResponse,
  ListTokensData,
  ListTokensError,
  ListTokensResponse,
  ListUpcomingSchedulesData,
  ListUpcomingSchedulesError,
  ListUpcomingSchedulesResponse,
  ListUsersData,
  ListUsersError,
  ListUsersResponse,
  ListVersionsData,
  ListVersionsError,
  ListVersionsResponse,
  LoginData,
  LoginError,
  LoginResponse,
  LogoutData,
  LogoutError,
  LogoutResponse,
  PushNamespaceBranchData,
  PushNamespaceBranchError,
  PushNamespaceBranchResponse,
  PutAiProviderData,
  PutAiProviderError,
  PutAiProviderResponse,
  PutGlobalSecretData,
  PutGlobalSecretError,
  PutGlobalSecretResponse,
  PutGlobalVariableData,
  PutGlobalVariableError,
  PutGlobalVariableResponse,
  PutNamespaceSecretData,
  PutNamespaceSecretError,
  PutNamespaceSecretResponse,
  PutNamespaceVariableData,
  PutNamespaceVariableError,
  PutNamespaceVariableResponse,
  RequestTriageData,
  RequestTriageError,
  RequestTriageResponse,
  RerunExecutionData,
  RerunExecutionError,
  RerunExecutionResponse,
  ResetUserPasswordData,
  ResetUserPasswordError,
  ResetUserPasswordResponse,
  RestartExecutionData,
  RestartExecutionError,
  RestartExecutionResponse,
  RevertVersionData,
  RevertVersionError,
  RevertVersionResponse,
  RevokeOtherSessionsData,
  RevokeOtherSessionsError,
  RevokeOtherSessionsResponse,
  RevokeTokenData,
  RevokeTokenError,
  RevokeTokenResponse,
  RotateWebhookKeyData,
  RotateWebhookKeyError,
  RotateWebhookKeyResponse,
  RunFileData,
  RunFileError,
  RunFileResponse,
  RunnerCompleteData,
  RunnerCompleteError,
  RunnerCompleteResponse,
  RunnerGetBundleData,
  RunnerGetBundleResponse,
  RunnerGetSpecData,
  RunnerGetSpecError,
  RunnerGetSpecResponse,
  RunnerHeartbeatData,
  RunnerHeartbeatError,
  RunnerHeartbeatResponse2,
  RunnerPostEventsData,
  RunnerPostEventsError,
  RunnerPostEventsResponse,
  RunnerPostLogsData,
  RunnerPostLogsError,
  RunnerPostLogsResponse,
  RunnerPutArtifactData,
  RunnerPutArtifactResponse,
  SaveChangesData,
  SaveChangesError,
  SaveChangesResponse,
  SyncGitSourceData,
  SyncGitSourceError,
  TestAiProviderData,
  TestAiProviderError,
  TestAiProviderResponse,
  TriggerFlowData,
  TriggerFlowError,
  TriggerFlowResponse,
  UpdateFlowData,
  UpdateFlowError,
  UpdateFlowResponse,
  UpdateGitSourceData,
  UpdateGitSourceError,
  UpdateGitSourceResponse,
  UpdateMeData,
  UpdateMeError,
  UpdateMeResponse,
  UpdateSecretProviderData,
  UpdateSecretProviderError,
  UpdateSecretProviderResponse,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
  UploadFileData,
  ValidateFileData,
  ValidateFileError,
  ValidateFileResponse,
} from "../types.gen";

export const runnerPutArtifactMutation = (
  options?: Partial<Options<RunnerPutArtifactData>>,
): UseMutationOptions<
  RunnerPutArtifactResponse,
  DefaultError,
  Options<RunnerPutArtifactData>
> => {
  const mutationOptions: UseMutationOptions<
    RunnerPutArtifactResponse,
    DefaultError,
    Options<RunnerPutArtifactData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await runnerPutArtifact({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const runnerGetBundleQueryKey = (
  options: Options<RunnerGetBundleData>,
) => createQueryKey("runnerGetBundle", options);

export const runnerGetBundleOptions = (options: Options<RunnerGetBundleData>) =>
  queryOptions<
    RunnerGetBundleResponse,
    DefaultError,
    RunnerGetBundleResponse,
    ReturnType<typeof runnerGetBundleQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await runnerGetBundle({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: runnerGetBundleQueryKey(options),
  });

export const runnerCompleteMutation = (
  options?: Partial<Options<RunnerCompleteData>>,
): UseMutationOptions<
  RunnerCompleteResponse,
  RunnerCompleteError,
  Options<RunnerCompleteData>
> => {
  const mutationOptions: UseMutationOptions<
    RunnerCompleteResponse,
    RunnerCompleteError,
    Options<RunnerCompleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await runnerComplete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const runnerPostEventsMutation = (
  options?: Partial<Options<RunnerPostEventsData>>,
): UseMutationOptions<
  RunnerPostEventsResponse,
  RunnerPostEventsError,
  Options<RunnerPostEventsData>
> => {
  const mutationOptions: UseMutationOptions<
    RunnerPostEventsResponse,
    RunnerPostEventsError,
    Options<RunnerPostEventsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await runnerPostEvents({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const runnerHeartbeatMutation = (
  options?: Partial<Options<RunnerHeartbeatData>>,
): UseMutationOptions<
  RunnerHeartbeatResponse2,
  RunnerHeartbeatError,
  Options<RunnerHeartbeatData>
> => {
  const mutationOptions: UseMutationOptions<
    RunnerHeartbeatResponse2,
    RunnerHeartbeatError,
    Options<RunnerHeartbeatData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await runnerHeartbeat({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const runnerPostLogsMutation = (
  options?: Partial<Options<RunnerPostLogsData>>,
): UseMutationOptions<
  RunnerPostLogsResponse,
  RunnerPostLogsError,
  Options<RunnerPostLogsData>
> => {
  const mutationOptions: UseMutationOptions<
    RunnerPostLogsResponse,
    RunnerPostLogsError,
    Options<RunnerPostLogsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await runnerPostLogs({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const runnerGetSpecQueryKey = (options: Options<RunnerGetSpecData>) =>
  createQueryKey("runnerGetSpec", options);

export const runnerGetSpecOptions = (options: Options<RunnerGetSpecData>) =>
  queryOptions<
    RunnerGetSpecResponse,
    RunnerGetSpecError,
    RunnerGetSpecResponse,
    ReturnType<typeof runnerGetSpecQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await runnerGetSpec({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: runnerGetSpecQueryKey(options),
  });

export const listAiConversationsQueryKey = (
  options?: Options<ListAiConversationsData>,
) => createQueryKey("listAiConversations", options);

export const listAiConversationsOptions = (
  options?: Options<ListAiConversationsData>,
) =>
  queryOptions<
    ListAiConversationsResponse,
    ListAiConversationsError,
    ListAiConversationsResponse,
    ReturnType<typeof listAiConversationsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAiConversations({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAiConversationsQueryKey(options),
  });

export const createAiConversationMutation = (
  options?: Partial<Options<CreateAiConversationData>>,
): UseMutationOptions<
  CreateAiConversationResponse,
  CreateAiConversationError,
  Options<CreateAiConversationData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateAiConversationResponse,
    CreateAiConversationError,
    Options<CreateAiConversationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createAiConversation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteAiConversationMutation = (
  options?: Partial<Options<DeleteAiConversationData>>,
): UseMutationOptions<
  DeleteAiConversationResponse,
  DeleteAiConversationError,
  Options<DeleteAiConversationData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteAiConversationResponse,
    DeleteAiConversationError,
    Options<DeleteAiConversationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAiConversation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAiConversationQueryKey = (
  options: Options<GetAiConversationData>,
) => createQueryKey("getAiConversation", options);

export const getAiConversationOptions = (
  options: Options<GetAiConversationData>,
) =>
  queryOptions<
    GetAiConversationResponse,
    GetAiConversationError,
    GetAiConversationResponse,
    ReturnType<typeof getAiConversationQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAiConversation({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAiConversationQueryKey(options),
  });

export const deleteAiProviderMutation = (
  options?: Partial<Options<DeleteAiProviderData>>,
): UseMutationOptions<
  DeleteAiProviderResponse,
  DeleteAiProviderError,
  Options<DeleteAiProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteAiProviderResponse,
    DeleteAiProviderError,
    Options<DeleteAiProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAiProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAiProviderQueryKey = (options?: Options<GetAiProviderData>) =>
  createQueryKey("getAiProvider", options);

export const getAiProviderOptions = (options?: Options<GetAiProviderData>) =>
  queryOptions<
    GetAiProviderResponse,
    GetAiProviderError,
    GetAiProviderResponse,
    ReturnType<typeof getAiProviderQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAiProvider({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAiProviderQueryKey(options),
  });

export const putAiProviderMutation = (
  options?: Partial<Options<PutAiProviderData>>,
): UseMutationOptions<
  PutAiProviderResponse,
  PutAiProviderError,
  Options<PutAiProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    PutAiProviderResponse,
    PutAiProviderError,
    Options<PutAiProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putAiProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const testAiProviderMutation = (
  options?: Partial<Options<TestAiProviderData>>,
): UseMutationOptions<
  TestAiProviderResponse,
  TestAiProviderError,
  Options<TestAiProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    TestAiProviderResponse,
    TestAiProviderError,
    Options<TestAiProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await testAiProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAiStatusQueryKey = (options?: Options<GetAiStatusData>) =>
  createQueryKey("getAiStatus", options);

export const getAiStatusOptions = (options?: Options<GetAiStatusData>) =>
  queryOptions<
    GetAiStatusResponse,
    GetAiStatusError,
    GetAiStatusResponse,
    ReturnType<typeof getAiStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAiStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAiStatusQueryKey(options),
  });

export const listAuditEventsQueryKey = (
  options?: Options<ListAuditEventsData>,
) => createQueryKey("listAuditEvents", options);

export const listAuditEventsOptions = (
  options?: Options<ListAuditEventsData>,
) =>
  queryOptions<
    ListAuditEventsResponse,
    ListAuditEventsError,
    ListAuditEventsResponse,
    ReturnType<typeof listAuditEventsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAuditEvents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAuditEventsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listAuditEventsInfiniteQueryKey = (
  options?: Options<ListAuditEventsData>,
): QueryKey<Options<ListAuditEventsData>> =>
  createQueryKey("listAuditEvents", options, true);

export const listAuditEventsInfiniteOptions = (
  options?: Options<ListAuditEventsData>,
) => {
  const opts = infiniteQueryOptions<
    ListAuditEventsResponse,
    ListAuditEventsError,
    InfiniteData<ListAuditEventsResponse>,
    QueryKey<Options<ListAuditEventsData>>,
    | string
    | Pick<
        QueryKey<Options<ListAuditEventsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListAuditEventsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listAuditEvents({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listAuditEventsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

export const loginMutation = (
  options?: Partial<Options<LoginData>>,
): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
  const mutationOptions: UseMutationOptions<
    LoginResponse,
    LoginError,
    Options<LoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await login({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const logoutMutation = (
  options?: Partial<Options<LogoutData>>,
): UseMutationOptions<LogoutResponse, LogoutError, Options<LogoutData>> => {
  const mutationOptions: UseMutationOptions<
    LogoutResponse,
    LogoutError,
    Options<LogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMeQueryKey = (options?: Options<GetMeData>) =>
  createQueryKey("getMe", options);

export const getMeOptions = (options?: Options<GetMeData>) =>
  queryOptions<
    GetMeResponse,
    GetMeError,
    GetMeResponse,
    ReturnType<typeof getMeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMeQueryKey(options),
  });

export const updateMeMutation = (
  options?: Partial<Options<UpdateMeData>>,
): UseMutationOptions<
  UpdateMeResponse,
  UpdateMeError,
  Options<UpdateMeData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateMeResponse,
    UpdateMeError,
    Options<UpdateMeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateMe({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const changePasswordMutation = (
  options?: Partial<Options<ChangePasswordData>>,
): UseMutationOptions<
  ChangePasswordResponse,
  ChangePasswordError,
  Options<ChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    ChangePasswordResponse,
    ChangePasswordError,
    Options<ChangePasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await changePassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const revokeOtherSessionsMutation = (
  options?: Partial<Options<RevokeOtherSessionsData>>,
): UseMutationOptions<
  RevokeOtherSessionsResponse,
  RevokeOtherSessionsError,
  Options<RevokeOtherSessionsData>
> => {
  const mutationOptions: UseMutationOptions<
    RevokeOtherSessionsResponse,
    RevokeOtherSessionsError,
    Options<RevokeOtherSessionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await revokeOtherSessions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listExecutionsQueryKey = (options?: Options<ListExecutionsData>) =>
  createQueryKey("listExecutions", options);

export const listExecutionsOptions = (options?: Options<ListExecutionsData>) =>
  queryOptions<
    ListExecutionsResponse,
    ListExecutionsError,
    ListExecutionsResponse,
    ReturnType<typeof listExecutionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listExecutions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listExecutionsQueryKey(options),
  });

export const listExecutionsInfiniteQueryKey = (
  options?: Options<ListExecutionsData>,
): QueryKey<Options<ListExecutionsData>> =>
  createQueryKey("listExecutions", options, true);

export const listExecutionsInfiniteOptions = (
  options?: Options<ListExecutionsData>,
) => {
  const opts = infiniteQueryOptions<
    ListExecutionsResponse,
    ListExecutionsError,
    InfiniteData<ListExecutionsResponse>,
    QueryKey<Options<ListExecutionsData>>,
    | string
    | Pick<
        QueryKey<Options<ListExecutionsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListExecutionsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listExecutions({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listExecutionsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

export const getExecutionQueryKey = (options: Options<GetExecutionData>) =>
  createQueryKey("getExecution", options);

export const getExecutionOptions = (options: Options<GetExecutionData>) =>
  queryOptions<
    GetExecutionResponse,
    GetExecutionError,
    GetExecutionResponse,
    ReturnType<typeof getExecutionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExecution({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExecutionQueryKey(options),
  });

export const listExecutionArtifactsQueryKey = (
  options: Options<ListExecutionArtifactsData>,
) => createQueryKey("listExecutionArtifacts", options);

export const listExecutionArtifactsOptions = (
  options: Options<ListExecutionArtifactsData>,
) =>
  queryOptions<
    ListExecutionArtifactsResponse,
    ListExecutionArtifactsError,
    ListExecutionArtifactsResponse,
    ReturnType<typeof listExecutionArtifactsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listExecutionArtifacts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listExecutionArtifactsQueryKey(options),
  });

export const downloadArtifactQueryKey = (
  options: Options<DownloadArtifactData>,
) => createQueryKey("downloadArtifact", options);

export const downloadArtifactOptions = (
  options: Options<DownloadArtifactData>,
) =>
  queryOptions<
    DownloadArtifactResponse,
    DefaultError,
    DownloadArtifactResponse,
    ReturnType<typeof downloadArtifactQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await downloadArtifact({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: downloadArtifactQueryKey(options),
  });

export const cancelExecutionMutation = (
  options?: Partial<Options<CancelExecutionData>>,
): UseMutationOptions<
  CancelExecutionResponse,
  CancelExecutionError,
  Options<CancelExecutionData>
> => {
  const mutationOptions: UseMutationOptions<
    CancelExecutionResponse,
    CancelExecutionError,
    Options<CancelExecutionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cancelExecution({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listExecutionInsightsQueryKey = (
  options: Options<ListExecutionInsightsData>,
) => createQueryKey("listExecutionInsights", options);

export const listExecutionInsightsOptions = (
  options: Options<ListExecutionInsightsData>,
) =>
  queryOptions<
    ListExecutionInsightsResponse,
    ListExecutionInsightsError,
    ListExecutionInsightsResponse,
    ReturnType<typeof listExecutionInsightsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listExecutionInsights({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listExecutionInsightsQueryKey(options),
  });

export const requestTriageMutation = (
  options?: Partial<Options<RequestTriageData>>,
): UseMutationOptions<
  RequestTriageResponse,
  RequestTriageError,
  Options<RequestTriageData>
> => {
  const mutationOptions: UseMutationOptions<
    RequestTriageResponse,
    RequestTriageError,
    Options<RequestTriageData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await requestTriage({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExecutionLogsQueryKey = (
  options: Options<GetExecutionLogsData>,
) => createQueryKey("getExecutionLogs", options);

export const getExecutionLogsOptions = (
  options: Options<GetExecutionLogsData>,
) =>
  queryOptions<
    GetExecutionLogsResponse,
    GetExecutionLogsError,
    GetExecutionLogsResponse,
    ReturnType<typeof getExecutionLogsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExecutionLogs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExecutionLogsQueryKey(options),
  });

export const getExecutionLogsInfiniteQueryKey = (
  options: Options<GetExecutionLogsData>,
): QueryKey<Options<GetExecutionLogsData>> =>
  createQueryKey("getExecutionLogs", options, true);

export const getExecutionLogsInfiniteOptions = (
  options: Options<GetExecutionLogsData>,
) => {
  const opts = infiniteQueryOptions<
    GetExecutionLogsResponse,
    GetExecutionLogsError,
    InfiniteData<GetExecutionLogsResponse>,
    QueryKey<Options<GetExecutionLogsData>>,
    | string
    | Pick<
        QueryKey<Options<GetExecutionLogsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetExecutionLogsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getExecutionLogs({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getExecutionLogsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

export const downloadExecutionLogsQueryKey = (
  options: Options<DownloadExecutionLogsData>,
) => createQueryKey("downloadExecutionLogs", options);

export const downloadExecutionLogsOptions = (
  options: Options<DownloadExecutionLogsData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof downloadExecutionLogsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await downloadExecutionLogs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: downloadExecutionLogsQueryKey(options),
  });

export const listExecutionMetricsQueryKey = (
  options: Options<ListExecutionMetricsData>,
) => createQueryKey("listExecutionMetrics", options);

export const listExecutionMetricsOptions = (
  options: Options<ListExecutionMetricsData>,
) =>
  queryOptions<
    ListExecutionMetricsResponse,
    ListExecutionMetricsError,
    ListExecutionMetricsResponse,
    ReturnType<typeof listExecutionMetricsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listExecutionMetrics({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listExecutionMetricsQueryKey(options),
  });

export const rerunExecutionMutation = (
  options?: Partial<Options<RerunExecutionData>>,
): UseMutationOptions<
  RerunExecutionResponse,
  RerunExecutionError,
  Options<RerunExecutionData>
> => {
  const mutationOptions: UseMutationOptions<
    RerunExecutionResponse,
    RerunExecutionError,
    Options<RerunExecutionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await rerunExecution({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const restartExecutionMutation = (
  options?: Partial<Options<RestartExecutionData>>,
): UseMutationOptions<
  RestartExecutionResponse,
  RestartExecutionError,
  Options<RestartExecutionData>
> => {
  const mutationOptions: UseMutationOptions<
    RestartExecutionResponse,
    RestartExecutionError,
    Options<RestartExecutionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await restartExecution({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listFlowsQueryKey = (options?: Options<ListFlowsData>) =>
  createQueryKey("listFlows", options);

export const listFlowsOptions = (options?: Options<ListFlowsData>) =>
  queryOptions<
    ListFlowsResponse,
    ListFlowsError,
    ListFlowsResponse,
    ReturnType<typeof listFlowsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFlows({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFlowsQueryKey(options),
  });

export const listFlowsInfiniteQueryKey = (
  options?: Options<ListFlowsData>,
): QueryKey<Options<ListFlowsData>> =>
  createQueryKey("listFlows", options, true);

export const listFlowsInfiniteOptions = (options?: Options<ListFlowsData>) => {
  const opts = infiniteQueryOptions<
    ListFlowsResponse,
    ListFlowsError,
    InfiniteData<ListFlowsResponse>,
    QueryKey<Options<ListFlowsData>>,
    | string
    | Pick<
        QueryKey<Options<ListFlowsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListFlowsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listFlows({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listFlowsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

export const getFlowQueryKey = (options: Options<GetFlowData>) =>
  createQueryKey("getFlow", options);

export const getFlowOptions = (options: Options<GetFlowData>) =>
  queryOptions<
    GetFlowResponse,
    GetFlowError,
    GetFlowResponse,
    ReturnType<typeof getFlowQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFlow({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFlowQueryKey(options),
  });

export const updateFlowMutation = (
  options?: Partial<Options<UpdateFlowData>>,
): UseMutationOptions<
  UpdateFlowResponse,
  UpdateFlowError,
  Options<UpdateFlowData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateFlowResponse,
    UpdateFlowError,
    Options<UpdateFlowData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateFlow({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const diffFlowRevisionsQueryKey = (
  options: Options<DiffFlowRevisionsData>,
) => createQueryKey("diffFlowRevisions", options);

export const diffFlowRevisionsOptions = (
  options: Options<DiffFlowRevisionsData>,
) =>
  queryOptions<
    DiffFlowRevisionsResponse,
    DiffFlowRevisionsError,
    DiffFlowRevisionsResponse,
    ReturnType<typeof diffFlowRevisionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await diffFlowRevisions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: diffFlowRevisionsQueryKey(options),
  });

export const triggerFlowMutation = (
  options?: Partial<Options<TriggerFlowData>>,
): UseMutationOptions<
  TriggerFlowResponse,
  TriggerFlowError,
  Options<TriggerFlowData>
> => {
  const mutationOptions: UseMutationOptions<
    TriggerFlowResponse,
    TriggerFlowError,
    Options<TriggerFlowData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await triggerFlow({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFlowMetricsQueryKey = (options: Options<GetFlowMetricsData>) =>
  createQueryKey("getFlowMetrics", options);

export const getFlowMetricsOptions = (options: Options<GetFlowMetricsData>) =>
  queryOptions<
    GetFlowMetricsResponse,
    GetFlowMetricsError,
    GetFlowMetricsResponse,
    ReturnType<typeof getFlowMetricsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFlowMetrics({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFlowMetricsQueryKey(options),
  });

export const listFlowRevisionsQueryKey = (
  options: Options<ListFlowRevisionsData>,
) => createQueryKey("listFlowRevisions", options);

export const listFlowRevisionsOptions = (
  options: Options<ListFlowRevisionsData>,
) =>
  queryOptions<
    ListFlowRevisionsResponse,
    ListFlowRevisionsError,
    ListFlowRevisionsResponse,
    ReturnType<typeof listFlowRevisionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFlowRevisions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFlowRevisionsQueryKey(options),
  });

export const getFlowRevisionQueryKey = (
  options: Options<GetFlowRevisionData>,
) => createQueryKey("getFlowRevision", options);

export const getFlowRevisionOptions = (options: Options<GetFlowRevisionData>) =>
  queryOptions<
    GetFlowRevisionResponse,
    GetFlowRevisionError,
    GetFlowRevisionResponse,
    ReturnType<typeof getFlowRevisionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFlowRevision({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFlowRevisionQueryKey(options),
  });

export const getFlowStatsQueryKey = (options: Options<GetFlowStatsData>) =>
  createQueryKey("getFlowStats", options);

export const getFlowStatsOptions = (options: Options<GetFlowStatsData>) =>
  queryOptions<
    GetFlowStatsResponse,
    GetFlowStatsError,
    GetFlowStatsResponse,
    ReturnType<typeof getFlowStatsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFlowStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFlowStatsQueryKey(options),
  });

export const rotateWebhookKeyMutation = (
  options?: Partial<Options<RotateWebhookKeyData>>,
): UseMutationOptions<
  RotateWebhookKeyResponse,
  RotateWebhookKeyError,
  Options<RotateWebhookKeyData>
> => {
  const mutationOptions: UseMutationOptions<
    RotateWebhookKeyResponse,
    RotateWebhookKeyError,
    Options<RotateWebhookKeyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await rotateWebhookKey({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listGitSourcesQueryKey = (options?: Options<ListGitSourcesData>) =>
  createQueryKey("listGitSources", options);

export const listGitSourcesOptions = (options?: Options<ListGitSourcesData>) =>
  queryOptions<
    ListGitSourcesResponse,
    ListGitSourcesError,
    ListGitSourcesResponse,
    ReturnType<typeof listGitSourcesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listGitSources({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listGitSourcesQueryKey(options),
  });

export const createGitSourceMutation = (
  options?: Partial<Options<CreateGitSourceData>>,
): UseMutationOptions<
  CreateGitSourceResponse,
  CreateGitSourceError,
  Options<CreateGitSourceData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateGitSourceResponse,
    CreateGitSourceError,
    Options<CreateGitSourceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createGitSource({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteGitSourceMutation = (
  options?: Partial<Options<DeleteGitSourceData>>,
): UseMutationOptions<
  DeleteGitSourceResponse,
  DeleteGitSourceError,
  Options<DeleteGitSourceData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteGitSourceResponse,
    DeleteGitSourceError,
    Options<DeleteGitSourceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteGitSource({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getGitSourceQueryKey = (options: Options<GetGitSourceData>) =>
  createQueryKey("getGitSource", options);

export const getGitSourceOptions = (options: Options<GetGitSourceData>) =>
  queryOptions<
    GetGitSourceResponse,
    GetGitSourceError,
    GetGitSourceResponse,
    ReturnType<typeof getGitSourceQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGitSource({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGitSourceQueryKey(options),
  });

export const updateGitSourceMutation = (
  options?: Partial<Options<UpdateGitSourceData>>,
): UseMutationOptions<
  UpdateGitSourceResponse,
  UpdateGitSourceError,
  Options<UpdateGitSourceData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateGitSourceResponse,
    UpdateGitSourceError,
    Options<UpdateGitSourceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateGitSource({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listGitSyncRunsQueryKey = (
  options: Options<ListGitSyncRunsData>,
) => createQueryKey("listGitSyncRuns", options);

export const listGitSyncRunsOptions = (options: Options<ListGitSyncRunsData>) =>
  queryOptions<
    ListGitSyncRunsResponse,
    ListGitSyncRunsError,
    ListGitSyncRunsResponse,
    ReturnType<typeof listGitSyncRunsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listGitSyncRuns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listGitSyncRunsQueryKey(options),
  });

export const syncGitSourceMutation = (
  options?: Partial<Options<SyncGitSourceData>>,
): UseMutationOptions<
  unknown,
  SyncGitSourceError,
  Options<SyncGitSourceData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    SyncGitSourceError,
    Options<SyncGitSourceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await syncGitSource({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listInstancesQueryKey = (options?: Options<ListInstancesData>) =>
  createQueryKey("listInstances", options);

export const listInstancesOptions = (options?: Options<ListInstancesData>) =>
  queryOptions<
    ListInstancesResponse,
    ListInstancesError,
    ListInstancesResponse,
    ReturnType<typeof listInstancesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listInstances({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listInstancesQueryKey(options),
  });

export const listNamespacesQueryKey = (options?: Options<ListNamespacesData>) =>
  createQueryKey("listNamespaces", options);

export const listNamespacesOptions = (options?: Options<ListNamespacesData>) =>
  queryOptions<
    ListNamespacesResponse,
    ListNamespacesError,
    ListNamespacesResponse,
    ReturnType<typeof listNamespacesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listNamespaces({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listNamespacesQueryKey(options),
  });

export const createNamespaceMutation = (
  options?: Partial<Options<CreateNamespaceData>>,
): UseMutationOptions<
  CreateNamespaceResponse,
  CreateNamespaceError,
  Options<CreateNamespaceData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateNamespaceResponse,
    CreateNamespaceError,
    Options<CreateNamespaceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createNamespace({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteNamespaceMutation = (
  options?: Partial<Options<DeleteNamespaceData>>,
): UseMutationOptions<
  DeleteNamespaceResponse,
  DeleteNamespaceError,
  Options<DeleteNamespaceData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteNamespaceResponse,
    DeleteNamespaceError,
    Options<DeleteNamespaceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteNamespace({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getNamespaceQueryKey = (options: Options<GetNamespaceData>) =>
  createQueryKey("getNamespace", options);

export const getNamespaceOptions = (options: Options<GetNamespaceData>) =>
  queryOptions<
    GetNamespaceResponse,
    GetNamespaceError,
    GetNamespaceResponse,
    ReturnType<typeof getNamespaceQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getNamespace({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getNamespaceQueryKey(options),
  });

export const saveChangesMutation = (
  options?: Partial<Options<SaveChangesData>>,
): UseMutationOptions<
  SaveChangesResponse,
  SaveChangesError,
  Options<SaveChangesData>
> => {
  const mutationOptions: UseMutationOptions<
    SaveChangesResponse,
    SaveChangesError,
    Options<SaveChangesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await saveChanges({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const diffVersionsQueryKey = (options: Options<DiffVersionsData>) =>
  createQueryKey("diffVersions", options);

export const diffVersionsOptions = (options: Options<DiffVersionsData>) =>
  queryOptions<
    DiffVersionsResponse,
    DiffVersionsError,
    DiffVersionsResponse,
    ReturnType<typeof diffVersionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await diffVersions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: diffVersionsQueryKey(options),
  });

export const getFileQueryKey = (options: Options<GetFileData>) =>
  createQueryKey("getFile", options);

export const getFileOptions = (options: Options<GetFileData>) =>
  queryOptions<
    GetFileResponse,
    DefaultError,
    GetFileResponse,
    ReturnType<typeof getFileQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFileQueryKey(options),
  });

export const uploadFileMutation = (
  options?: Partial<Options<UploadFileData>>,
): UseMutationOptions<unknown, DefaultError, Options<UploadFileData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<UploadFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await uploadFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listFilesQueryKey = (options: Options<ListFilesData>) =>
  createQueryKey("listFiles", options);

export const listFilesOptions = (options: Options<ListFilesData>) =>
  queryOptions<
    ListFilesResponse,
    ListFilesError,
    ListFilesResponse,
    ReturnType<typeof listFilesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFilesQueryKey(options),
  });

export const getNamespaceGitQueryKey = (
  options: Options<GetNamespaceGitData>,
) => createQueryKey("getNamespaceGit", options);

export const getNamespaceGitOptions = (options: Options<GetNamespaceGitData>) =>
  queryOptions<
    GetNamespaceGitResponse,
    GetNamespaceGitError,
    GetNamespaceGitResponse,
    ReturnType<typeof getNamespaceGitQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getNamespaceGit({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getNamespaceGitQueryKey(options),
  });

export const pushNamespaceBranchMutation = (
  options?: Partial<Options<PushNamespaceBranchData>>,
): UseMutationOptions<
  PushNamespaceBranchResponse,
  PushNamespaceBranchError,
  Options<PushNamespaceBranchData>
> => {
  const mutationOptions: UseMutationOptions<
    PushNamespaceBranchResponse,
    PushNamespaceBranchError,
    Options<PushNamespaceBranchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await pushNamespaceBranch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const revertVersionMutation = (
  options?: Partial<Options<RevertVersionData>>,
): UseMutationOptions<
  RevertVersionResponse,
  RevertVersionError,
  Options<RevertVersionData>
> => {
  const mutationOptions: UseMutationOptions<
    RevertVersionResponse,
    RevertVersionError,
    Options<RevertVersionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await revertVersion({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const runFileMutation = (
  options?: Partial<Options<RunFileData>>,
): UseMutationOptions<RunFileResponse, RunFileError, Options<RunFileData>> => {
  const mutationOptions: UseMutationOptions<
    RunFileResponse,
    RunFileError,
    Options<RunFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await runFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listNamespaceSecretsQueryKey = (
  options: Options<ListNamespaceSecretsData>,
) => createQueryKey("listNamespaceSecrets", options);

export const listNamespaceSecretsOptions = (
  options: Options<ListNamespaceSecretsData>,
) =>
  queryOptions<
    ListNamespaceSecretsResponse,
    ListNamespaceSecretsError,
    ListNamespaceSecretsResponse,
    ReturnType<typeof listNamespaceSecretsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listNamespaceSecrets({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listNamespaceSecretsQueryKey(options),
  });

export const deleteNamespaceSecretMutation = (
  options?: Partial<Options<DeleteNamespaceSecretData>>,
): UseMutationOptions<
  DeleteNamespaceSecretResponse,
  DeleteNamespaceSecretError,
  Options<DeleteNamespaceSecretData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteNamespaceSecretResponse,
    DeleteNamespaceSecretError,
    Options<DeleteNamespaceSecretData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteNamespaceSecret({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const putNamespaceSecretMutation = (
  options?: Partial<Options<PutNamespaceSecretData>>,
): UseMutationOptions<
  PutNamespaceSecretResponse,
  PutNamespaceSecretError,
  Options<PutNamespaceSecretData>
> => {
  const mutationOptions: UseMutationOptions<
    PutNamespaceSecretResponse,
    PutNamespaceSecretError,
    Options<PutNamespaceSecretData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putNamespaceSecret({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const checkNamespaceSecretMutation = (
  options?: Partial<Options<CheckNamespaceSecretData>>,
): UseMutationOptions<
  CheckNamespaceSecretResponse,
  CheckNamespaceSecretError,
  Options<CheckNamespaceSecretData>
> => {
  const mutationOptions: UseMutationOptions<
    CheckNamespaceSecretResponse,
    CheckNamespaceSecretError,
    Options<CheckNamespaceSecretData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await checkNamespaceSecret({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const validateFileMutation = (
  options?: Partial<Options<ValidateFileData>>,
): UseMutationOptions<
  ValidateFileResponse,
  ValidateFileError,
  Options<ValidateFileData>
> => {
  const mutationOptions: UseMutationOptions<
    ValidateFileResponse,
    ValidateFileError,
    Options<ValidateFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await validateFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listNamespaceVariablesQueryKey = (
  options: Options<ListNamespaceVariablesData>,
) => createQueryKey("listNamespaceVariables", options);

export const listNamespaceVariablesOptions = (
  options: Options<ListNamespaceVariablesData>,
) =>
  queryOptions<
    ListNamespaceVariablesResponse,
    ListNamespaceVariablesError,
    ListNamespaceVariablesResponse,
    ReturnType<typeof listNamespaceVariablesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listNamespaceVariables({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listNamespaceVariablesQueryKey(options),
  });

export const deleteNamespaceVariableMutation = (
  options?: Partial<Options<DeleteNamespaceVariableData>>,
): UseMutationOptions<
  DeleteNamespaceVariableResponse,
  DeleteNamespaceVariableError,
  Options<DeleteNamespaceVariableData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteNamespaceVariableResponse,
    DeleteNamespaceVariableError,
    Options<DeleteNamespaceVariableData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteNamespaceVariable({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const putNamespaceVariableMutation = (
  options?: Partial<Options<PutNamespaceVariableData>>,
): UseMutationOptions<
  PutNamespaceVariableResponse,
  PutNamespaceVariableError,
  Options<PutNamespaceVariableData>
> => {
  const mutationOptions: UseMutationOptions<
    PutNamespaceVariableResponse,
    PutNamespaceVariableError,
    Options<PutNamespaceVariableData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putNamespaceVariable({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listVersionsQueryKey = (options: Options<ListVersionsData>) =>
  createQueryKey("listVersions", options);

export const listVersionsOptions = (options: Options<ListVersionsData>) =>
  queryOptions<
    ListVersionsResponse,
    ListVersionsError,
    ListVersionsResponse,
    ReturnType<typeof listVersionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listVersions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listVersionsQueryKey(options),
  });

export const listUpcomingSchedulesQueryKey = (
  options?: Options<ListUpcomingSchedulesData>,
) => createQueryKey("listUpcomingSchedules", options);

export const listUpcomingSchedulesOptions = (
  options?: Options<ListUpcomingSchedulesData>,
) =>
  queryOptions<
    ListUpcomingSchedulesResponse,
    ListUpcomingSchedulesError,
    ListUpcomingSchedulesResponse,
    ReturnType<typeof listUpcomingSchedulesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUpcomingSchedules({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listUpcomingSchedulesQueryKey(options),
  });

export const getFlowSchemaQueryKey = (options?: Options<GetFlowSchemaData>) =>
  createQueryKey("getFlowSchema", options);

export const getFlowSchemaOptions = (options?: Options<GetFlowSchemaData>) =>
  queryOptions<
    unknown,
    GetFlowSchemaError,
    unknown,
    ReturnType<typeof getFlowSchemaQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFlowSchema({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFlowSchemaQueryKey(options),
  });

export const listSecretProvidersQueryKey = (
  options?: Options<ListSecretProvidersData>,
) => createQueryKey("listSecretProviders", options);

export const listSecretProvidersOptions = (
  options?: Options<ListSecretProvidersData>,
) =>
  queryOptions<
    ListSecretProvidersResponse,
    ListSecretProvidersError,
    ListSecretProvidersResponse,
    ReturnType<typeof listSecretProvidersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listSecretProviders({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listSecretProvidersQueryKey(options),
  });

export const createSecretProviderMutation = (
  options?: Partial<Options<CreateSecretProviderData>>,
): UseMutationOptions<
  CreateSecretProviderResponse,
  CreateSecretProviderError,
  Options<CreateSecretProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSecretProviderResponse,
    CreateSecretProviderError,
    Options<CreateSecretProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSecretProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteSecretProviderMutation = (
  options?: Partial<Options<DeleteSecretProviderData>>,
): UseMutationOptions<
  DeleteSecretProviderResponse,
  DeleteSecretProviderError,
  Options<DeleteSecretProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteSecretProviderResponse,
    DeleteSecretProviderError,
    Options<DeleteSecretProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteSecretProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const updateSecretProviderMutation = (
  options?: Partial<Options<UpdateSecretProviderData>>,
): UseMutationOptions<
  UpdateSecretProviderResponse,
  UpdateSecretProviderError,
  Options<UpdateSecretProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSecretProviderResponse,
    UpdateSecretProviderError,
    Options<UpdateSecretProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateSecretProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const checkSecretProviderMutation = (
  options?: Partial<Options<CheckSecretProviderData>>,
): UseMutationOptions<
  CheckSecretProviderResponse,
  CheckSecretProviderError,
  Options<CheckSecretProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    CheckSecretProviderResponse,
    CheckSecretProviderError,
    Options<CheckSecretProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await checkSecretProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listGlobalSecretsQueryKey = (
  options?: Options<ListGlobalSecretsData>,
) => createQueryKey("listGlobalSecrets", options);

export const listGlobalSecretsOptions = (
  options?: Options<ListGlobalSecretsData>,
) =>
  queryOptions<
    ListGlobalSecretsResponse,
    ListGlobalSecretsError,
    ListGlobalSecretsResponse,
    ReturnType<typeof listGlobalSecretsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listGlobalSecrets({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listGlobalSecretsQueryKey(options),
  });

export const deleteGlobalSecretMutation = (
  options?: Partial<Options<DeleteGlobalSecretData>>,
): UseMutationOptions<
  DeleteGlobalSecretResponse,
  DeleteGlobalSecretError,
  Options<DeleteGlobalSecretData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteGlobalSecretResponse,
    DeleteGlobalSecretError,
    Options<DeleteGlobalSecretData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteGlobalSecret({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const putGlobalSecretMutation = (
  options?: Partial<Options<PutGlobalSecretData>>,
): UseMutationOptions<
  PutGlobalSecretResponse,
  PutGlobalSecretError,
  Options<PutGlobalSecretData>
> => {
  const mutationOptions: UseMutationOptions<
    PutGlobalSecretResponse,
    PutGlobalSecretError,
    Options<PutGlobalSecretData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putGlobalSecret({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const checkGlobalSecretMutation = (
  options?: Partial<Options<CheckGlobalSecretData>>,
): UseMutationOptions<
  CheckGlobalSecretResponse,
  CheckGlobalSecretError,
  Options<CheckGlobalSecretData>
> => {
  const mutationOptions: UseMutationOptions<
    CheckGlobalSecretResponse,
    CheckGlobalSecretError,
    Options<CheckGlobalSecretData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await checkGlobalSecret({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getDashboardQueryKey = (options?: Options<GetDashboardData>) =>
  createQueryKey("getDashboard", options);

export const getDashboardOptions = (options?: Options<GetDashboardData>) =>
  queryOptions<
    GetDashboardResponse,
    GetDashboardError,
    GetDashboardResponse,
    ReturnType<typeof getDashboardQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDashboard({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDashboardQueryKey(options),
  });

export const getStorageStatusQueryKey = (
  options?: Options<GetStorageStatusData>,
) => createQueryKey("getStorageStatus", options);

export const getStorageStatusOptions = (
  options?: Options<GetStorageStatusData>,
) =>
  queryOptions<
    GetStorageStatusResponse,
    GetStorageStatusError,
    GetStorageStatusResponse,
    ReturnType<typeof getStorageStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStorageStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStorageStatusQueryKey(options),
  });

export const listTokensQueryKey = (options?: Options<ListTokensData>) =>
  createQueryKey("listTokens", options);

export const listTokensOptions = (options?: Options<ListTokensData>) =>
  queryOptions<
    ListTokensResponse,
    ListTokensError,
    ListTokensResponse,
    ReturnType<typeof listTokensQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTokens({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTokensQueryKey(options),
  });

export const listTokensInfiniteQueryKey = (
  options?: Options<ListTokensData>,
): QueryKey<Options<ListTokensData>> =>
  createQueryKey("listTokens", options, true);

export const listTokensInfiniteOptions = (
  options?: Options<ListTokensData>,
) => {
  const opts = infiniteQueryOptions<
    ListTokensResponse,
    ListTokensError,
    InfiniteData<ListTokensResponse>,
    QueryKey<Options<ListTokensData>>,
    | string
    | Pick<
        QueryKey<Options<ListTokensData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListTokensData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listTokens({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listTokensInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

export const createTokenMutation = (
  options?: Partial<Options<CreateTokenData>>,
): UseMutationOptions<
  CreateTokenResponse,
  CreateTokenError,
  Options<CreateTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTokenResponse,
    CreateTokenError,
    Options<CreateTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const revokeTokenMutation = (
  options?: Partial<Options<RevokeTokenData>>,
): UseMutationOptions<
  RevokeTokenResponse,
  RevokeTokenError,
  Options<RevokeTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    RevokeTokenResponse,
    RevokeTokenError,
    Options<RevokeTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await revokeToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) =>
  createQueryKey("listUsers", options);

export const listUsersOptions = (options?: Options<ListUsersData>) =>
  queryOptions<
    ListUsersResponse,
    ListUsersError,
    ListUsersResponse,
    ReturnType<typeof listUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listUsersQueryKey(options),
  });

export const listUsersInfiniteQueryKey = (
  options?: Options<ListUsersData>,
): QueryKey<Options<ListUsersData>> =>
  createQueryKey("listUsers", options, true);

export const listUsersInfiniteOptions = (options?: Options<ListUsersData>) => {
  const opts = infiniteQueryOptions<
    ListUsersResponse,
    ListUsersError,
    InfiniteData<ListUsersResponse>,
    QueryKey<Options<ListUsersData>>,
    | string
    | Pick<
        QueryKey<Options<ListUsersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListUsersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listUsersInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

export const createUserMutation = (
  options?: Partial<Options<CreateUserData>>,
): UseMutationOptions<
  CreateUserResponse,
  CreateUserError,
  Options<CreateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserResponse,
    CreateUserError,
    Options<CreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const updateUserMutation = (
  options?: Partial<Options<UpdateUserData>>,
): UseMutationOptions<
  UpdateUserResponse,
  UpdateUserError,
  Options<UpdateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateUserResponse,
    UpdateUserError,
    Options<UpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const resetUserPasswordMutation = (
  options?: Partial<Options<ResetUserPasswordData>>,
): UseMutationOptions<
  ResetUserPasswordResponse,
  ResetUserPasswordError,
  Options<ResetUserPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    ResetUserPasswordResponse,
    ResetUserPasswordError,
    Options<ResetUserPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await resetUserPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listGlobalVariablesQueryKey = (
  options?: Options<ListGlobalVariablesData>,
) => createQueryKey("listGlobalVariables", options);

export const listGlobalVariablesOptions = (
  options?: Options<ListGlobalVariablesData>,
) =>
  queryOptions<
    ListGlobalVariablesResponse,
    ListGlobalVariablesError,
    ListGlobalVariablesResponse,
    ReturnType<typeof listGlobalVariablesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listGlobalVariables({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listGlobalVariablesQueryKey(options),
  });

export const deleteGlobalVariableMutation = (
  options?: Partial<Options<DeleteGlobalVariableData>>,
): UseMutationOptions<
  DeleteGlobalVariableResponse,
  DeleteGlobalVariableError,
  Options<DeleteGlobalVariableData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteGlobalVariableResponse,
    DeleteGlobalVariableError,
    Options<DeleteGlobalVariableData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteGlobalVariable({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const putGlobalVariableMutation = (
  options?: Partial<Options<PutGlobalVariableData>>,
): UseMutationOptions<
  PutGlobalVariableResponse,
  PutGlobalVariableError,
  Options<PutGlobalVariableData>
> => {
  const mutationOptions: UseMutationOptions<
    PutGlobalVariableResponse,
    PutGlobalVariableError,
    Options<PutGlobalVariableData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putGlobalVariable({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Request a sync of a git source from a push webhook
 */
export const gitWebhookMutation = (
  options?: Partial<Options<GitWebhookData>>,
): UseMutationOptions<unknown, DefaultError, Options<GitWebhookData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<GitWebhookData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await gitWebhook({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Start the flow of a webhook trigger
 */
export const fireWebhookMutation = (
  options?: Partial<Options<FireWebhookData>>,
): UseMutationOptions<unknown, DefaultError, Options<FireWebhookData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<FireWebhookData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await fireWebhook({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
