// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package aidb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const activeInsightExists = `-- name: ActiveInsightExists :one
SELECT EXISTS (SELECT 1 FROM ai_insights WHERE execution_id = $1 AND status IN ('pending', 'running'))
`

func (q *Queries) ActiveInsightExists(ctx context.Context, executionID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, activeInsightExists, executionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const claimInsight = `-- name: ClaimInsight :one
UPDATE ai_insights SET status = 'running'
WHERE id = (SELECT i.id FROM ai_insights i WHERE i.status = 'pending' ORDER BY i.created_at, i.id FOR UPDATE SKIP LOCKED LIMIT 1)
RETURNING id, execution_id, kind, status, summary, probable_cause, evidence, suggested_fix, confidence, model, error, created_at
`

func (q *Queries) ClaimInsight(ctx context.Context) (AiInsight, error) {
	row := q.db.QueryRow(ctx, claimInsight)
	var i AiInsight
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.Kind,
		&i.Status,
		&i.Summary,
		&i.ProbableCause,
		&i.Evidence,
		&i.SuggestedFix,
		&i.Confidence,
		&i.Model,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO ai_conversations (id, user_id, title, created_at) VALUES ($1, $2, $3, $4) RETURNING id, user_id, title, created_at
`

type CreateConversationParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	CreatedAt time.Time
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (AiConversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.CreatedAt,
	)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const decidePendingAction = `-- name: DecidePendingAction :one
UPDATE ai_pending_actions SET status = $3, decided_by = $4, decided_at = $5
WHERE id = $1 AND conversation_id = $2 AND status = 'pending'
RETURNING id, conversation_id, tool_call_id, tool, arguments, status, decided_by, decided_at, created_at
`

type DecidePendingActionParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Status         string
	DecidedBy      *uuid.UUID
	DecidedAt      *time.Time
}

func (q *Queries) DecidePendingAction(ctx context.Context, arg DecidePendingActionParams) (AiPendingAction, error) {
	row := q.db.QueryRow(ctx, decidePendingAction,
		arg.ID,
		arg.ConversationID,
		arg.Status,
		arg.DecidedBy,
		arg.DecidedAt,
	)
	var i AiPendingAction
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ToolCallID,
		&i.Tool,
		&i.Arguments,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM ai_conversations WHERE id = $1 AND user_id = $2
`

type DeleteConversationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSetting = `-- name: DeleteSetting :execrows
DELETE FROM settings WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStaleInsights = `-- name: FailStaleInsights :execrows
UPDATE ai_insights SET status = 'failed', error = 'the triage stopped before it ended'
WHERE status = 'running' AND created_at < $1
`

func (q *Queries) FailStaleInsights(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleInsights, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishInsight = `-- name: FinishInsight :exec
UPDATE ai_insights SET status = $2, summary = $3, probable_cause = $4, evidence = $5, suggested_fix = $6,
    confidence = $7, model = $8, error = $9
WHERE id = $1
`

type FinishInsightParams struct {
	ID            uuid.UUID
	Status        string
	Summary       string
	ProbableCause string
	Evidence      json.RawMessage
	SuggestedFix  string
	Confidence    string
	Model         string
	Error         string
}

func (q *Queries) FinishInsight(ctx context.Context, arg FinishInsightParams) error {
	_, err := q.db.Exec(ctx, finishInsight,
		arg.ID,
		arg.Status,
		arg.Summary,
		arg.ProbableCause,
		arg.Evidence,
		arg.SuggestedFix,
		arg.Confidence,
		arg.Model,
		arg.Error,
	)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, created_at FROM ai_conversations WHERE id = $1 AND user_id = $2
`

type GetConversationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (AiConversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.UserID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const insertInsight = `-- name: InsertInsight :exec
INSERT INTO ai_insights (id, execution_id, kind, status, created_at) VALUES ($1, $2, 'triage', 'pending', $3)
`

type InsertInsightParams struct {
	ID          uuid.UUID
	ExecutionID uuid.UUID
	CreatedAt   time.Time
}

func (q *Queries) InsertInsight(ctx context.Context, arg InsertInsightParams) error {
	_, err := q.db.Exec(ctx, insertInsight, arg.ID, arg.ExecutionID, arg.CreatedAt)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO ai_messages (id, conversation_id, role, content, created_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertMessageParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        json.RawMessage
	CreatedAt      time.Time
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const insertPendingAction = `-- name: InsertPendingAction :exec
INSERT INTO ai_pending_actions (id, conversation_id, tool_call_id, tool, arguments, status, created_at)
VALUES ($1, $2, $3, $4, $5, 'pending', $6)
`

type InsertPendingActionParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	ToolCallID     string
	Tool           string
	Arguments      json.RawMessage
	CreatedAt      time.Time
}

func (q *Queries) InsertPendingAction(ctx context.Context, arg InsertPendingActionParams) error {
	_, err := q.db.Exec(ctx, insertPendingAction,
		arg.ID,
		arg.ConversationID,
		arg.ToolCallID,
		arg.Tool,
		arg.Arguments,
		arg.CreatedAt,
	)
	return err
}

const listConversations = `-- name: ListConversations :many
SELECT id, user_id, title, created_at FROM ai_conversations WHERE user_id = $1 ORDER BY created_at DESC, id DESC LIMIT $2
`

type ListConversationsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]AiConversation, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiConversation{}
	for rows.Next() {
		var i AiConversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsights = `-- name: ListInsights :many
SELECT id, execution_id, kind, status, summary, probable_cause, evidence, suggested_fix, confidence, model, error, created_at FROM ai_insights WHERE execution_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListInsights(ctx context.Context, executionID uuid.UUID) ([]AiInsight, error) {
	rows, err := q.db.Query(ctx, listInsights, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiInsight{}
	for rows.Next() {
		var i AiInsight
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.Kind,
			&i.Status,
			&i.Summary,
			&i.ProbableCause,
			&i.Evidence,
			&i.SuggestedFix,
			&i.Confidence,
			&i.Model,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, content, created_at FROM ai_messages WHERE conversation_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListMessages(ctx context.Context, conversationID uuid.UUID) ([]AiMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiMessage{}
	for rows.Next() {
		var i AiMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingActions = `-- name: ListPendingActions :many
SELECT id, conversation_id, tool_call_id, tool, arguments, status, decided_by, decided_at, created_at FROM ai_pending_actions WHERE conversation_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListPendingActions(ctx context.Context, conversationID uuid.UUID) ([]AiPendingAction, error) {
	rows, err := q.db.Query(ctx, listPendingActions, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiPendingAction{}
	for rows.Next() {
		var i AiPendingAction
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.ToolCallID,
			&i.Tool,
			&i.Arguments,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value, updated_by, updated_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = EXCLUDED.updated_at
`

type PutSettingParams struct {
	Key       string
	Value     json.RawMessage
	UpdatedBy string
	UpdatedAt time.Time
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.Exec(ctx, putSetting,
		arg.Key,
		arg.Value,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const setConversationTitle = `-- name: SetConversationTitle :exec
UPDATE ai_conversations SET title = $2 WHERE id = $1 AND title = ''
`

type SetConversationTitleParams struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) SetConversationTitle(ctx context.Context, arg SetConversationTitleParams) error {
	_, err := q.db.Exec(ctx, setConversationTitle, arg.ID, arg.Title)
	return err
}
