// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package variabledb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteVariable = `-- name: DeleteVariable :execrows
DELETE FROM variables WHERE namespace_id IS NOT DISTINCT FROM $1 AND key = $2
`

type DeleteVariableParams struct {
	NamespaceID *uuid.UUID
	Key         string
}

func (q *Queries) DeleteVariable(ctx context.Context, arg DeleteVariableParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVariable, arg.NamespaceID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listVariables = `-- name: ListVariables :many
SELECT v.key, v.value, coalesce(n.name, '')::text AS scope, v.updated_by, v.updated_at
FROM variables v
LEFT JOIN namespaces n ON n.id = v.namespace_id
WHERE v.namespace_id IS NULL OR (n.name = ANY($1::text[]) AND n.deleted_at IS NULL)
ORDER BY v.key
`

type ListVariablesRow struct {
	Key       string
	Value     string
	Scope     string
	UpdatedBy string
	UpdatedAt time.Time
}

// Variables of the global scope and of the namespaces in chain. An empty chain lists only global variables.
func (q *Queries) ListVariables(ctx context.Context, chain []string) ([]ListVariablesRow, error) {
	rows, err := q.db.Query(ctx, listVariables, chain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariablesRow{}
	for rows.Next() {
		var i ListVariablesRow
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Scope,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const namespaceID = `-- name: NamespaceID :one
SELECT id FROM namespaces WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) NamespaceID(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, namespaceID, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertVariable = `-- name: UpsertVariable :one
INSERT INTO variables (id, namespace_id, key, value, updated_by, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (namespace_id, key) DO UPDATE SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = EXCLUDED.updated_at
RETURNING (xmax = 0)::boolean AS created
`

type UpsertVariableParams struct {
	ID          uuid.UUID
	NamespaceID *uuid.UUID
	Key         string
	Value       string
	Actor       string
	Now         time.Time
}

func (q *Queries) UpsertVariable(ctx context.Context, arg UpsertVariableParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertVariable,
		arg.ID,
		arg.NamespaceID,
		arg.Key,
		arg.Value,
		arg.Actor,
		arg.Now,
	)
	var created bool
	err := row.Scan(&created)
	return created, err
}
