// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gitsyncdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimSync = `-- name: ClaimSync :execrows
UPDATE git_sources SET last_sync_status = 'running', sync_requested_at = NULL, last_sync_at = $1
WHERE id = $2 AND last_sync_status <> 'running'
    AND EXISTS (SELECT 1 FROM leases WHERE name = 'git-sync' AND holder = $3 AND expires_at > $1)
`

type ClaimSyncParams struct {
	Now    *time.Time
	ID     uuid.UUID
	Holder string
}

// A leader-only write: the lease check and the claim are one statement (REQ-CORE-006).
func (q *Queries) ClaimSync(ctx context.Context, arg ClaimSyncParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimSync, arg.Now, arg.ID, arg.Holder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMappings = `-- name: DeleteMappings :exec
DELETE FROM git_mappings WHERE git_source_id = $1
`

func (q *Queries) DeleteMappings(ctx context.Context, gitSourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMappings, gitSourceID)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM git_sources WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const dueSources = `-- name: DueSources :many
SELECT id FROM git_sources
WHERE sync_requested_at IS NOT NULL OR last_sync_at IS NULL OR last_sync_at + poll_interval * interval '1 second' <= $1
ORDER BY sync_requested_at NULLS LAST, last_sync_at NULLS FIRST
LIMIT 20
`

// Sources with a requested sync, or whose poll interval passed since the last sync.
func (q *Queries) DueSources(ctx context.Context, now *time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dueSources, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishRun = `-- name: FinishRun :exec
UPDATE git_sync_runs SET ended_at = $1, sha = $2, status = $3, error = $4,
    warnings = $5, snapshots_created = $6
WHERE id = $7
`

type FinishRunParams struct {
	EndedAt          *time.Time
	Sha              string
	Status           string
	Error            string
	Warnings         json.RawMessage
	SnapshotsCreated int32
	ID               uuid.UUID
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.Exec(ctx, finishRun,
		arg.EndedAt,
		arg.Sha,
		arg.Status,
		arg.Error,
		arg.Warnings,
		arg.SnapshotsCreated,
		arg.ID,
	)
	return err
}

const finishSync = `-- name: FinishSync :exec
UPDATE git_sources SET last_sync_status = $1, last_error = $2, last_sync_at = $3,
    last_synced_sha = CASE WHEN $1::text = 'success' THEN $4::text ELSE last_synced_sha END
WHERE id = $5
`

type FinishSyncParams struct {
	Status string
	Error  string
	Now    *time.Time
	Sha    string
	ID     uuid.UUID
}

func (q *Queries) FinishSync(ctx context.Context, arg FinishSyncParams) error {
	_, err := q.db.Exec(ctx, finishSync,
		arg.Status,
		arg.Error,
		arg.Now,
		arg.Sha,
		arg.ID,
	)
	return err
}

const getSource = `-- name: GetSource :one
SELECT id, name, repo_url, branch, auth_type, credential_secret_key, known_hosts, poll_interval, webhook_secret_key, last_synced_sha, last_sync_at, last_sync_status, last_error, sync_requested_at, created_at FROM git_sources WHERE id = $1
`

func (q *Queries) GetSource(ctx context.Context, id uuid.UUID) (GitSource, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i GitSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.AuthType,
		&i.CredentialSecretKey,
		&i.KnownHosts,
		&i.PollInterval,
		&i.WebhookSecretKey,
		&i.LastSyncedSha,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastError,
		&i.SyncRequestedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceByName = `-- name: GetSourceByName :one
SELECT id, name, repo_url, branch, auth_type, credential_secret_key, known_hosts, poll_interval, webhook_secret_key, last_synced_sha, last_sync_at, last_sync_status, last_error, sync_requested_at, created_at FROM git_sources WHERE name = $1
`

func (q *Queries) GetSourceByName(ctx context.Context, name string) (GitSource, error) {
	row := q.db.QueryRow(ctx, getSourceByName, name)
	var i GitSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.AuthType,
		&i.CredentialSecretKey,
		&i.KnownHosts,
		&i.PollInterval,
		&i.WebhookSecretKey,
		&i.LastSyncedSha,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastError,
		&i.SyncRequestedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertMapping = `-- name: InsertMapping :exec
INSERT INTO git_mappings (git_source_id, repo_path, namespace_id) VALUES ($1, $2, $3)
`

type InsertMappingParams struct {
	GitSourceID uuid.UUID
	RepoPath    string
	NamespaceID uuid.UUID
}

func (q *Queries) InsertMapping(ctx context.Context, arg InsertMappingParams) error {
	_, err := q.db.Exec(ctx, insertMapping, arg.GitSourceID, arg.RepoPath, arg.NamespaceID)
	return err
}

const insertRun = `-- name: InsertRun :exec
INSERT INTO git_sync_runs (id, git_source_id, started_at, status) VALUES ($1, $2, $3, 'running')
`

type InsertRunParams struct {
	ID          uuid.UUID
	GitSourceID uuid.UUID
	StartedAt   time.Time
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.Exec(ctx, insertRun, arg.ID, arg.GitSourceID, arg.StartedAt)
	return err
}

const insertSource = `-- name: InsertSource :one
INSERT INTO git_sources (id, name, repo_url, branch, auth_type, credential_secret_key, known_hosts, poll_interval, webhook_secret_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10)
RETURNING id, name, repo_url, branch, auth_type, credential_secret_key, known_hosts, poll_interval, webhook_secret_key, last_synced_sha, last_sync_at, last_sync_status, last_error, sync_requested_at, created_at
`

type InsertSourceParams struct {
	ID                  uuid.UUID
	Name                string
	RepoUrl             string
	Branch              string
	AuthType            string
	CredentialSecretKey string
	KnownHosts          string
	PollInterval        int32
	WebhookSecretKey    string
	Now                 time.Time
}

func (q *Queries) InsertSource(ctx context.Context, arg InsertSourceParams) (GitSource, error) {
	row := q.db.QueryRow(ctx, insertSource,
		arg.ID,
		arg.Name,
		arg.RepoUrl,
		arg.Branch,
		arg.AuthType,
		arg.CredentialSecretKey,
		arg.KnownHosts,
		arg.PollInterval,
		arg.WebhookSecretKey,
		arg.Now,
	)
	var i GitSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.AuthType,
		&i.CredentialSecretKey,
		&i.KnownHosts,
		&i.PollInterval,
		&i.WebhookSecretKey,
		&i.LastSyncedSha,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastError,
		&i.SyncRequestedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMappings = `-- name: ListMappings :many
SELECT m.git_source_id, m.repo_path, m.namespace_id, n.name AS namespace
FROM git_mappings m
JOIN namespaces n ON n.id = m.namespace_id
WHERE m.git_source_id = $1
ORDER BY m.repo_path
`

type ListMappingsRow struct {
	GitSourceID uuid.UUID
	RepoPath    string
	NamespaceID uuid.UUID
	Namespace   string
}

func (q *Queries) ListMappings(ctx context.Context, gitSourceID uuid.UUID) ([]ListMappingsRow, error) {
	rows, err := q.db.Query(ctx, listMappings, gitSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMappingsRow{}
	for rows.Next() {
		var i ListMappingsRow
		if err := rows.Scan(
			&i.GitSourceID,
			&i.RepoPath,
			&i.NamespaceID,
			&i.Namespace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, git_source_id, started_at, ended_at, sha, status, error, warnings, snapshots_created FROM git_sync_runs WHERE git_source_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListRunsParams struct {
	GitSourceID uuid.UUID
	MaxRows     int32
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]GitSyncRun, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.GitSourceID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitSyncRun{}
	for rows.Next() {
		var i GitSyncRun
		if err := rows.Scan(
			&i.ID,
			&i.GitSourceID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Sha,
			&i.Status,
			&i.Error,
			&i.Warnings,
			&i.SnapshotsCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, name, repo_url, branch, auth_type, credential_secret_key, known_hosts, poll_interval, webhook_secret_key, last_synced_sha, last_sync_at, last_sync_status, last_error, sync_requested_at, created_at FROM git_sources ORDER BY name
`

func (q *Queries) ListSources(ctx context.Context) ([]GitSource, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitSource{}
	for rows.Next() {
		var i GitSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.Branch,
			&i.AuthType,
			&i.CredentialSecretKey,
			&i.KnownHosts,
			&i.PollInterval,
			&i.WebhookSecretKey,
			&i.LastSyncedSha,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastError,
			&i.SyncRequestedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const namespaceByName = `-- name: NamespaceByName :one
SELECT n.id, n.source_type, n.git_source_id, m.git_source_id AS mapped_by
FROM namespaces n
LEFT JOIN git_mappings m ON m.namespace_id = n.id
WHERE n.name = $1 AND n.deleted_at IS NULL
`

type NamespaceByNameRow struct {
	ID          uuid.UUID
	SourceType  string
	GitSourceID *uuid.UUID
	MappedBy    *uuid.UUID
}

func (q *Queries) NamespaceByName(ctx context.Context, name string) (NamespaceByNameRow, error) {
	row := q.db.QueryRow(ctx, namespaceByName, name)
	var i NamespaceByNameRow
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.GitSourceID,
		&i.MappedBy,
	)
	return i, err
}

const requestSync = `-- name: RequestSync :execrows
UPDATE git_sources SET sync_requested_at = $1 WHERE id = $2
`

type RequestSyncParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) RequestSync(ctx context.Context, arg RequestSyncParams) (int64, error) {
	result, err := q.db.Exec(ctx, requestSync, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetStaleRunning = `-- name: ResetStaleRunning :exec
UPDATE git_sources SET last_sync_status = 'failed', last_error = 'the sync stopped before it ended'
WHERE last_sync_status = 'running' AND last_sync_at < $1
`

// A sync that an instance left in running (for example after a crash) can run again.
func (q *Queries) ResetStaleRunning(ctx context.Context, before *time.Time) error {
	_, err := q.db.Exec(ctx, resetStaleRunning, before)
	return err
}

const setNamespaceSource = `-- name: SetNamespaceSource :exec
UPDATE namespaces SET git_source_id = $1 WHERE id = $2
`

type SetNamespaceSourceParams struct {
	GitSourceID *uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SetNamespaceSource(ctx context.Context, arg SetNamespaceSourceParams) error {
	_, err := q.db.Exec(ctx, setNamespaceSource, arg.GitSourceID, arg.ID)
	return err
}

const sourceOfNamespace = `-- name: SourceOfNamespace :one
SELECT s.id, s.name, s.repo_url, s.branch, s.auth_type, s.credential_secret_key, s.known_hosts, s.last_synced_sha,
    s.last_sync_at, s.last_sync_status, s.last_error, m.repo_path, n.id AS namespace_id
FROM git_sources s
JOIN git_mappings m ON m.git_source_id = s.id
JOIN namespaces n ON n.id = m.namespace_id
WHERE n.name = $1 AND n.deleted_at IS NULL
`

type SourceOfNamespaceRow struct {
	ID                  uuid.UUID
	Name                string
	RepoUrl             string
	Branch              string
	AuthType            string
	CredentialSecretKey string
	KnownHosts          string
	LastSyncedSha       string
	LastSyncAt          *time.Time
	LastSyncStatus      string
	LastError           string
	RepoPath            string
	NamespaceID         uuid.UUID
}

func (q *Queries) SourceOfNamespace(ctx context.Context, namespace string) (SourceOfNamespaceRow, error) {
	row := q.db.QueryRow(ctx, sourceOfNamespace, namespace)
	var i SourceOfNamespaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.AuthType,
		&i.CredentialSecretKey,
		&i.KnownHosts,
		&i.LastSyncedSha,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastError,
		&i.RepoPath,
		&i.NamespaceID,
	)
	return i, err
}

const updateSource = `-- name: UpdateSource :one
UPDATE git_sources SET repo_url = $1, branch = $2, auth_type = $3,
    credential_secret_key = $4, known_hosts = $5,
    poll_interval = $6, webhook_secret_key = $7
WHERE id = $8
RETURNING id, name, repo_url, branch, auth_type, credential_secret_key, known_hosts, poll_interval, webhook_secret_key, last_synced_sha, last_sync_at, last_sync_status, last_error, sync_requested_at, created_at
`

type UpdateSourceParams struct {
	RepoUrl             string
	Branch              string
	AuthType            string
	CredentialSecretKey string
	KnownHosts          string
	PollInterval        int32
	WebhookSecretKey    string
	ID                  uuid.UUID
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (GitSource, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.RepoUrl,
		arg.Branch,
		arg.AuthType,
		arg.CredentialSecretKey,
		arg.KnownHosts,
		arg.PollInterval,
		arg.WebhookSecretKey,
		arg.ID,
	)
	var i GitSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.AuthType,
		&i.CredentialSecretKey,
		&i.KnownHosts,
		&i.PollInterval,
		&i.WebhookSecretKey,
		&i.LastSyncedSha,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastError,
		&i.SyncRequestedAt,
		&i.CreatedAt,
	)
	return i, err
}
