// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package secretdb

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AiConversation struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	CreatedAt time.Time
}

type AiInsight struct {
	ID            uuid.UUID
	ExecutionID   uuid.UUID
	Kind          string
	Status        string
	Summary       string
	ProbableCause string
	Evidence      json.RawMessage
	SuggestedFix  string
	Confidence    string
	Model         string
	Error         string
	CreatedAt     time.Time
}

type AiMessage struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        json.RawMessage
	CreatedAt      time.Time
}

type AiPendingAction struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	ToolCallID     string
	Tool           string
	Arguments      json.RawMessage
	Status         string
	DecidedBy      *uuid.UUID
	DecidedAt      *time.Time
	CreatedAt      time.Time
}

type ApiToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	TokenHash  []byte
	Prefix     string
	Role       string
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type Artifact struct {
	ID          uuid.UUID
	ExecutionID uuid.UUID
	TaskRunID   uuid.UUID
	Name        string
	StorageKey  string
	Size        int64
	ContentType string
	CreatedAt   time.Time
}

type AuditEvent struct {
	ID         uuid.UUID
	Ts         time.Time
	ActorType  string
	ActorID    string
	Action     string
	TargetType string
	TargetID   string
	Details    json.RawMessage
	Ip         string
}

type Bundle struct {
	ManifestHash string
	StorageKey   string
	Size         int64
	LastUsedAt   time.Time
}

type Execution struct {
	ID                uuid.UUID
	NamespaceID       uuid.UUID
	FlowID            *uuid.UUID
	FlowRevisionID    *uuid.UUID
	SnapshotID        uuid.UUID
	State             string
	TriggerType       string
	TriggerID         *uuid.UUID
	ScheduledFor      *time.Time
	TriggerPayload    json.RawMessage
	Definition        json.RawMessage
	Inputs            json.RawMessage
	Labels            json.RawMessage
	Outputs           json.RawMessage
	Error             string
	Reason            string
	ParentExecutionID *uuid.UUID
	ParentTaskRunID   *uuid.UUID
	RestartOfID       *uuid.UUID
	ChainDepth        int32
	CreatedBy         string
	CreatedAt         time.Time
	StartedAt         *time.Time
	EndedAt           *time.Time
	DeadlineAt        *time.Time
	DurationMs        *int64
	SecretKeysUsed    []string
	LogArchived       bool
}

type FileObject struct {
	Hash      string
	Size      int64
	CreatedAt time.Time
}

type Flow struct {
	ID                uuid.UUID
	NamespaceID       uuid.UUID
	FlowKey           string
	Path              string
	CurrentRevisionID *uuid.UUID
	Valid             bool
	Disabled          bool
	CreatedAt         time.Time
	DeletedAt         *time.Time
}

type FlowRevision struct {
	ID         uuid.UUID
	FlowID     uuid.UUID
	SnapshotID uuid.UUID
	SourceHash string
	Source     string
	Path       string
	Definition json.RawMessage
	Errors     json.RawMessage
	CreatedAt  time.Time
}

type GitMapping struct {
	GitSourceID uuid.UUID
	RepoPath    string
	NamespaceID uuid.UUID
}

type GitSource struct {
	ID                  uuid.UUID
	Name                string
	RepoUrl             string
	Branch              string
	AuthType            string
	CredentialSecretKey string
	KnownHosts          string
	PollInterval        int32
	WebhookSecretKey    string
	LastSyncedSha       string
	LastSyncAt          *time.Time
	LastSyncStatus      string
	LastError           string
	SyncRequestedAt     *time.Time
	CreatedAt           time.Time
}

type GitSyncRun struct {
	ID               uuid.UUID
	GitSourceID      uuid.UUID
	StartedAt        time.Time
	EndedAt          *time.Time
	Sha              string
	Status           string
	Error            string
	Warnings         json.RawMessage
	SnapshotsCreated int32
}

type Instance struct {
	ID          uuid.UUID
	Hostname    string
	Version     string
	Pools       []string
	Executors   []string
	StartedAt   time.Time
	HeartbeatAt time.Time
}

type Lease struct {
	Name      string
	Holder    string
	ExpiresAt time.Time
}

type LogChunk struct {
	ID          int64
	TaskRunID   uuid.UUID
	ExecutionID uuid.UUID
	Seq         int32
	FirstLine   int64
	LineCount   int32
	Data        []byte
	CreatedAt   time.Time
}

type LoginAttempt struct {
	Email       string
	Ip          string
	AttemptedAt time.Time
	Success     bool
}

type Metric struct {
	ID          int64
	ExecutionID uuid.UUID
	TaskRunID   uuid.UUID
	FlowID      *uuid.UUID
	Name        string
	Value       float64
	Unit        string
	Tags        json.RawMessage
	Ts          time.Time
	Seq         int32
	Idx         int32
}

type Namespace struct {
	ID             uuid.UUID
	Name           string
	SourceType     string
	GitSourceID    *uuid.UUID
	HeadSnapshotID *uuid.UUID
	Description    string
	CreatedAt      time.Time
	DeletedAt      *time.Time
}

type RateLimit struct {
	Key         string
	WindowStart time.Time
	Count       int32
}

type Secret struct {
	ID             uuid.UUID
	NamespaceID    *uuid.UUID
	Key            string
	ProviderID     uuid.UUID
	ProviderRef    string
	Ciphertext     []byte
	KeyID          string
	Description    string
	CreatedBy      string
	UpdatedBy      string
	UpdatedAt      time.Time
	LastResolvedAt *time.Time
}

type SecretProvider struct {
	ID        uuid.UUID
	Name      string
	Type      string
	Config    json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	IDHash     []byte
	UserID     uuid.UUID
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	Ip         string
	UserAgent  string
}

type Setting struct {
	Key       string
	Value     json.RawMessage
	UpdatedBy string
	UpdatedAt time.Time
}

type Snapshot struct {
	ID           uuid.UUID
	NamespaceID  uuid.UUID
	Version      *int32
	GitSha       string
	ManifestHash string
	Message      string
	CreatedBy    *uuid.UUID
	CreatedAt    time.Time
}

type SnapshotFile struct {
	SnapshotID uuid.UUID
	Path       string
	Hash       string
	Size       int64
	Executable bool
}

type StorageChunk struct {
	Key  string
	Idx  int32
	Data []byte
}

type StorageObject struct {
	Key       string
	Size      int64
	CreatedAt time.Time
}

type TaskRun struct {
	ID               uuid.UUID
	ExecutionID      uuid.UUID
	TaskKey          string
	TaskType         string
	Attempt          int32
	State            string
	Reason           string
	ExecutorType     string
	Pool             string
	ClaimedBy        *uuid.UUID
	ExternalRef      string
	RunTokenHash     []byte
	TokenExpiresAt   *time.Time
	HeartbeatAt      *time.Time
	CancelRequested  bool
	NotBefore        *time.Time
	QueuedAt         *time.Time
	StartedAt        *time.Time
	EndedAt          *time.Time
	ExitCode         *int32
	Error            string
	Outputs          json.RawMessage
	ReusedFromID     *uuid.UUID
	ChildExecutionID *uuid.UUID
}

type Trigger struct {
	ID             uuid.UUID
	FlowID         uuid.UUID
	RevisionID     uuid.UUID
	TriggerKey     string
	Type           string
	Config         json.RawMessage
	WebhookKeyHash []byte
	NextFireAt     *time.Time
	LastFiredAt    *time.Time
	Active         bool
}

type User struct {
	ID                 uuid.UUID
	Email              string
	Name               string
	PasswordHash       string
	Role               string
	MustChangePassword bool
	DisabledAt         *time.Time
	CreatedAt          time.Time
	LastLoginAt        *time.Time
}

type Variable struct {
	ID          uuid.UUID
	NamespaceID *uuid.UUID
	Key         string
	Value       string
	UpdatedBy   string
	UpdatedAt   time.Time
}
