// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package auditdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteOldAuditEvents = `-- name: DeleteOldAuditEvents :execrows
DELETE FROM audit_events WHERE ts < $1
`

func (q *Queries) DeleteOldAuditEvents(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldAuditEvents, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (id, ts, actor_type, actor_id, action, target_type, target_id, details, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditEventParams struct {
	ID         uuid.UUID
	Ts         time.Time
	ActorType  string
	ActorID    string
	Action     string
	TargetType string
	TargetID   string
	Details    json.RawMessage
	Ip         string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.Ts,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.Ip,
	)
	return err
}
